embedding:
  manual_cluster: D:/data/default/manuel_cluster_mapping_word.json
  device: cuda
  text_model:
    text_en: 'Alibaba-NLP/gte-large-en-v1.5'
    text_fr: "dangvantuan/sentence-camembert-large" #'intfloat/multilingual-e5-large-instruct'
  picture_model: D:/data/models/peft_block23_vit_large_patch14_clip_224_280416
  prompt_name : clustering
  prompt:
      clustering: "You are an art expert grouping art piece description together: "
  text:
      batch_size : 24
  picture:
      batch_size : 92
  dim_reduc:
      params:
        umap_n_neighbors : 25
        umap_n_components : 64
  clustering:
    params:
      verbose: 0 #0 or 1 if 1 then plot clusters on projected embeddings
      min_cluster_size: 3 # minimal number of obs for hdbscan clustering
      cluster_selection_epsilon: 2
      n_words_cluster: 5 # number of words to caracterize the cluster
      min_samples : 5 # The number of samples in a neighbourhood for a point to be considered a core point.
