gpt:
  save_path: D:/data/llm_extracts/extraction/
  llm_model:
    groq: llama3-70b-8192 #llama3-8b-8192 free so no need of limiting - 30/Min
    open_ai: gpt-3.5-turbo #gpt-4o-mini
    local: lmstudio-community/Meta-Llama-3-8B-Instruct-GGUF
    google: gemini-1.5-flash
  seed: 1234
  llm_action: "extract"
  prompt_path: C:\Users\alarr\Documents\repos\hart\backend-art-analytics\src\dataclean\prompt_templates
