gpt:
  save_path: D:/data/llm_extracts/extraction/
  llm_model: 
    groq: llama3-70b-8192 #llama3-8b-8192 free so no need of limiting - 30/Min
    open_ai: gpt-3.5-turbo
    local: lmstudio-community/Meta-Llama-3-8B-Instruct-GGUF
    google: gemini-1.5-flash
  seed: 1234
  introduction: "You are an art document entity extraction specialist. \
                Given an art description, your role is to extract all the text values of the JSON schema. \
                - Before rendering the JSON, think step by step to make sure the entity name answers well the text value you will give. \
                - If no value related to the field is found, then render 'None'. \
                - Do not normalize any entity value.\
                - Translate all values in english and only english. \
                - Do not start your answer by Here is the extracted or Response, directly give the JSON output. Make sure all values are quoted."