services:
    flask_app:
        container_name: middle_api
        build:
            context: ./app
            dockerfile: dockerfile
        expose:
            - 8888
        volumes:
            - ./app:/app
            - ../global-schemas/schemas:/app/src/schemas
            - ../global-schemas/utils:/app/src/utils
            - ../global-schemas/constants:/app/src/constants
            - ../global-schemas/configs:/app/configs
        command: gunicorn --bind 0.0.0.0:8888 --workers 4 --threads 4 --timeout 120 app:app
        environment:
            - FLASK_ENV=development
        env_file:
            - ../global-schemas/.env
        restart: always
        networks:
            - shared_net

    nginx:
        image: nginx:latest
        container_name: middle_nginx
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        restart: always
        depends_on:
            - flask_app
        networks:
            - shared_net

    caddy:
        image: caddy:latest
        container_name: middle_caddy
        ports:
            - "443:443"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - caddy_data:/data
            - caddy_config:/config
        restart: always
        networks:
            - shared_net

networks:
  shared_net:
    external: true

volumes:
  caddy_data:
  caddy_config:
