---
repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2  # Specify the version of Black you want to use
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=1024']

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0  # Specify the version of detect-secrets you want to use
    hooks:
      - id: detect-secrets

  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.0-beta  # Specify the version of hadolint you want to use
    hooks:
      - id: hadolint

  - repo: https://github.com/lukasmartinelli/hadolint
    rev: v2.13.0-beta  # Specify the version of hadolint you want to use
    hooks:
      - id: hadolint

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1  # Specify the version of pre-commit-golang you want to use
    hooks:
      - id: golangci-lint

  - repo: https://github.com/PyCQA/pylint
    rev: v3.2.4  # Specify the version of pylint you want to use
    hooks:
      - id: pylint
        args: [--max-line-length=110]
        language_version: python3.12

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1  # Specify the version of mypy you want to use
    hooks:
      - id: mypy
        language_version: python3.12

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.9  # Specify the version of bandit you want to use
    hooks:
      - id: bandit
        args: [--recursive, .]
        language_version: python3.12
