version: '3.7'

services:
  back_app:
    build: 
      context: ./app
      dockerfile: dockerfile
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - redis
    expose:
      - 5000
    command: gunicorn --bind 0.0.0.0:5000 --workers 4 --threads 4 --timeout 120 app:app
    env_file:
      - ./app/.env
    restart: always

  worker:
    build: .
    command: celery -A app.tasks worker --loglevel=info
    depends_on:
      - redis
  nginx:
        image: nginx:latest
        container_name: nginx
        ports:    
          - 2000:2000
        volumes:
          - ./nginx.conf:/etc/nginx/conf.d/default.conf
        restart: always
        depends_on: 
          - back_app

  redis:
    image: "redis:alpine"