services:
    back_app:
        container_name: backend_api
        build:
            context: ./app
            dockerfile: dockerfile
        expose:
            - 5000
        command: gunicorn --bind 0.0.0.0:5000 --workers 4 --threads 4 --timeout 120 app:app
        volumes:
            - ./app:/app
            - ../global-schemas/src/utils:/app/src/utils
            - ../global-schemas/src/constants:/app/src/constants
            - ../global-schemas/src/schemas:/app/src/schemas
            - ../global-schemas/src/modelling/prompt_templates:/app/src/modelling/prompt_templates
            - ../global-schemas/configs:/app/configs
            - ../global-schemas/src/modelling/transformers:/app/src/modelling/transformers
        environment:
            - FLASK_ENV=flask_worker
            - ROOT_PATH=/app/data
        env_file:
            - ../global-schemas/.env
        restart: always
        networks:
            - shared_net
    nginx:
        image: nginx:latest
        container_name: back_nginx
        ports:
            - 2000:2000
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        restart: always
        depends_on:
            - back_app
        networks:
            - shared_net
    celery:
        build:
            context: ./celery
            dockerfile: dockerfile
        # user: celeryuser
        container_name: back_celery
        volumes:
            - ./app:/app
            - D:/data/models:/app/data/models
            - D:/data/default:/app/data/default
            - ../global-schemas/configs:/app/configs
            - ../global-schemas/src/utils:/app/src/utils
            - ../global-schemas/src/constants:/app/src/constants
            - ../global-schemas/src/schemas:/app/src/schemas
            - ../global-schemas/src/sql_queries:/app/src/sql_queries
            - ../global-schemas/src/modelling/transformers:/app/src/modelling/transformers
        command: 'celery -A src.backend.tasks worker --pool=solo --loglevel=info --concurrency=1'
        env_file:
            - ../global-schemas/.env
        environment:
            - FLASK_ENV=celery_worker
            - ROOT_PATH=/app/data
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
        networks:
            - shared_net

networks:
  shared_net:
    external: true
