services:
    chromadb:
        image: ghcr.io/chroma-core/chroma:latest
        ports:
            - 8000:8000
        volumes:
            - D:/data/chroma_db/chroma_data:/chroma/chroma
        healthcheck: 
            test: curl localhost:8000/api/v1/heartbeat || exit 1
            interval: 1000s
            retries: 2
            start_period: 5s
            timeout: 10s
        networks:
            - net
    back_app:
        container_name: backend_api
        build: 
            context: ./app
            dockerfile: dockerfile
        expose:
            - 5000
        command: gunicorn --bind 0.0.0.0:5000 --workers 4 --threads 4 --timeout 120 app:app
        volumes: 
            - ./app:/app
        environment:
            - FLASK_ENV=flask_worker
        env_file:
            - ./.env
        restart: always
        networks:
            - net
    nginx:
        image: nginx:latest
        container_name: back_nginx
        ports:    
            - 2000:2000
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        restart: always
        depends_on: 
            - back_app
        networks:
            - net
    celery:
        build:
            context: ./celery
            dockerfile: dockerfile
        # user: celeryuser
        volumes:
            - ./app:/app
            - D:/data/models:/data/models
            - D:/data/default:/data/default
        command: celery -A src.backend.tasks worker --pool=solo --loglevel=info --concurrency=1
        depends_on:
            - redis
            - chromadb
        env_file:
            - ./.env
        environment:
            - FLASK_ENV=celery_worker
            - DB_HOST=chromadb
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
        networks:
            - net
    redis:
        image: "redis:alpine"
        networks:
            - net
    # flower:
    #     image: zoomeranalytics/flower:0.9.1-4.0.2
    #     restart: "no"
    #     env_file:
    #         - ./.env
    #     ports:
    #     - "5555:5555"
    #     depends_on:
    #     - redis

networks:
  net:
    driver: bridge