version: '3.7'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.api 
    depends_on:
      - redis
    command: flask run --host=0.0.0.0

  worker:
    build: .
    command: celery -A app.tasks worker --loglevel=info
    depends_on:
      - redis

  redis:
    image: "redis:alpine"