
class_mapping = {
    "tableau figuratif": "tableau",
    "livre": "livre",
    "alcool vin": "vin",
    "temps montre": "montre",
    "monnaie": "monnaie",
    "assiette": "assiette",
    "dessin": "dessin",
    "bijou collier": "collier",
    "tapis": "tapis",
    "chaise": "chaise",
    "temps horloge": "horloge",
    "litterature": "litterature",
    "tableau moderne": "tableau",
    "temps gousset": "gousset",
    "tableau nature_morte": "tableau",
    "photographie": "photographie",
    "tableau portrait": "tableau",
    "sculpture bronze": "sculpture",
    "theiere": "theiere",
    "plat metallique": "plat",
    "gravure": "gravure",
    "appareil_photo": "appareil_photo",
    "bijou broche": "broche",
    "tableau religieux": "tableau",
    "vetement foulard": "vetement",
    "verre": "verre",
    "bijou bracelet": "bracelet",
    "BD": "BD",
    "timbre": "timbre",
    "couverts divers": "couverts divers",
    "sculpture masque": "masque",
    "voiture miniature": "voiture_miniature",
    "affiche": "affiche",
    "bijou pierre": "pierre_precieuse",
    "bijou bague diamant": "bague",
    "sculpture petite porcelaine": "sculpture",
    "bijou boucle_oreille": "boucle_oreille",
    "medaille": "medaille",
    "meuble commode": "commode",
    "tasse porcelaine": "tasse",
    "carte": "carte",
    "sculpture asiatique": "sculpture",
    "bijou bague emeraude": "bague",
    "cadre": "cadre",
    "stylo": "stylo",
    "billet": "billet",
    "musique vinyle": "vinyle",
    "chaussure": "chaussure",
    "dessin asiatique": "dessin_asiatique",
    "evantail": "evantail",
    "arme feu pistolet": "pistolet",
    "petite_boite": "boite",
    "meuble vaisselier": "vaisselier",
    "meuble armoire": "armoire",
    "alcool autre": "alcool_autre",
    "candelabre bourgeois": "candelabre",
    "miroir": "miroir",
    "arme feu fusil": "fusil",
    "sculpture afrique": "sculpture",
    "bijou bague rubis": "bague",
    "miniature_train": "miniature_train",
    "alcool champagne": "champagne",
    "bol porcelaine": "bol",
    "poupee": "poupee",
    "lampe applique": "applique",
    "couverts coffret": "couverts",
    "sac": "sac",
    "sculpture bronze animalier": "sculpture",
    "candelabre": "candelabre",
    "peluche": "peluche",
    "theiere procelaine": "theiere",
    "figurine jouet": "jouet",
    "vase cameo": "vase",
    "meuble paravent": "paravent",
    "bijou bague saphir": "bague",
    "timbale": "timbale",
    "table basse": "table",
    "violon": "violon",
    "maquette bateau": "maquette_bateau",
    "vase bouteille": "vase",
    "arme blanche epee": "epee",
    "sculpture buste": "sculpture",
    "snuff_bottle_asia": "snuff_bottle",
    "sculpture blanche": "sculpture",
    "temps pendule": "pendule",
    "fossile": "fossile",
    "dessin planche BD": "dessin",
    "bijou bouton_manchette": "bouton_manchette",
    "table chevet": "table",
    "bijou bague perle": "bague",
    "chaise tabouret": "tabouret",
    "tapisserie": "tapisserie",
    "vase baluster_asie": "vase",
    "casque": "casque",
    "canne": "canne",
    "soupiere": "soupiere",
    "tire bouchon": "tire_bouchon",
    "canape": "canape",
    "vase porcelaine_vieux_paris": "vase",
    "autographe": "autographe",
    "canape banquette": "canape",
    "table gueridon": "table",
    "epingle cravate": "epingle_cravate",
    "etui_cigarette": "etui_cigarette",
    "crucifix": "crucifix",
    "vetement maillot sport": "vetement_maillot_sport",
    "food vessel": "vessel",
    "coffret": "coffret",
    "temps reveil": "reveil",
    "carte_pokemon": "carte_pokemon",
    "table bureau": "bureau",
    "saucier": "saucier",
    "pierre sculptée": "sculpture",
    "sac LV": "sac",
    "saliere_poivriere": "saliere_poivriere",
    "vetement vison": "vetement",
    "ceinture": "ceinture",
    "table console": "console",
    "lustre": "lustre",
    "vetement kimono": "kimono",
    "parfum": "parfum",
    "lampe plafonnier": "plafonnier",
    "meuble coffre": "coffre",
    "inro": "inro",
    "table pliee": "table",
    "lit bordure": "lit_bordure",
    "mapmonde": "mapmonde",
    "voiture": "voiture",
    "table salon ronde": "table",
    "arme blanche couteau": "couteau",
    "couverts louche": "couverts",
    "vase terre_cuite grece": "vase",
    "sculpture figurine oiseau porcelaine": "sculpture",
    "vetement robe longue": "vetement",
    "soupiere faience": "soupiere",
    "caligraphie asiatique": "caligraphie_asiatique",
    "sculpture colonne": "colonne",
    "tissu": "tissu",
    "archers": "archers",
    "paniere": "paniere",
    "bijou bracelet or": "bracelet",
    "vetement manteau long": "vetement",
    "briquet": "briquet",
    "pipes": "pipes",
    "lunette soleil": "lunette_soleil",
    "valise": "valise",
    "bijou pendentif medaillon": "pendentif",
    "sculpture personnage polychrome": "sculpture",
    "sac channel": "sac",
    "partition musique": "partition_musique",
    "trophe": "trophe",
    "vase potterie_ancienne": "vase",
    "jumelle": "jumelle",
    "huilier": "huilier",
    "lampe applique moderne": "applique",
    "cendrier": "cendrier",
    "icone": "icone",
    "guitare electrique": "guitare",
    "vase jarre": "vase",
    "service boisson": "carafon",
    "vase potterie_laquee": "vase",
    "skateboard": "skateboard",
    "vetement chapeau": "chapeau",
    "microscope": "microscope",
    "vase verre_couleur": "vase",
    "lampe napoleon3": "lampe",
    "boussole": "boussole",
    "table gigogne": "table_gigogne",
    "lampe art_nouveau": "lampe",
    "mortier": "mortier",
    "meuble paravent simple": "paravent",
    "vetement chandaille": "vetement",
    "bijou pendentif": "pendentif",
    "maquette avion": "maquette_avion",
    "cadre cheminee": "cadre_cheminee",
    "chaussure botte": "botte",
    "lampe bureau": "lampe",
    "jeu_echec": "jeu_echec",
    "plaque_immatriculation": "plaque",
    "papillon": "papillon",
    "banc": "banc",
    "cle": "cle",
    "vase medicis exterieur": "vase",
    "lingot": "lingot",
    "casserole": "casserole",
    "porte manteau": "porte_manteau",
    "parapluie": "parapluie",
    "machine_ecrire": "machine_ecrire",
    "vase verre": "vase",
    "sonophone": "sonophone",
    "vetement tailleur": "vetement",
    "meuble chiffonnier": "chiffonnier",
    "cloche": "cloche",
    "vase medicis": "vase",
    "balance": "balance",
    "guitare": "guitare",
    "radio": "radio",
    "vetement jupe": "vetement",
    "table bureau ormoulu": "bureau",
    "lampe gaz": "lampe",
    "repose buche": "repose_buche",
    "impression": "impression",
    "rond_serviette": "rond_serviette",
    "vetement pull": "vetement",
    "sac hermes": "sac",
    "lampadaire": "lampadaire",
    "table salon rectangulaire": "table",
    "vase bronze": "vase",
    "porte_monnaie": "porte_monnaie",
    "animal empaille": "animal_empaille",
    "sismographe": "sismographe",
    "vase couvert_asie": "vase",
    "cendrier non metal": "cendrier_non_metal",
    "moto": "moto",
    "vetement tunique": "vetement",
    "fauteuil louis_15": "fauteuil",
    "sablier": "sablier",
    "cruche potterie": "cruche",
    "couverts couteau": "couverts",
    "console applique": "console_applique",
    "carafon": "carafon",
    "vetement aube": "vetement",
    "radius vernier": "radius_vernier",
    "katana": "katana",
    "bijou bague ambre": "bague",
    "saucier porcelaine": "saucier",
    "brushpot": "brushpot",
    "lustre verre": "lustre",
    "tasse metal": "tasse",
    "lampe vase asiatique": "lampe_vase",
    "vase pablo_picasso": "vase_pablo_picasso",
    "couverts pince": "couverts",
    "cigare": "cigare",
    "lampe pied geometrique": "lampe",
    "miroir personnel": "miroir_personnel",
    "bijou bague autre": "bague",
    "piano": "piano",
    "brosse": "brosse",
    "stool porcelaine": "tabouret",
    "fauteuil allonge": "fauteuil",
    "fauteuil cuir": "fauteuil",
    "telescope": "telescope",
    "balle baseball": "balle_baseball",
    "harpe": "harpe",
    "pot porcelaine": "pot",
    "velo": "velo",
    "mooflask_asie": "mooflask_asie",
    "fauteuil contemporain": "fauteuil",
    "canape banc": "canape",
    "lampe tiffany": "lampe_tiffany",
    "telephone": "telephone",
    "lampe annee60": "lampe",
    "wine vessel": "vessel",
    "casque moto": "casque_moto",
    "cadre photo": "cadre_photo",
    "cor": "cor",
    "fauteuil 18eme": "fauteuil",
    "lunette vue": "lunette_vue",
    "pot porcelaine tabac": "pot",
    "lampe plafonnier cercle": "plafonnier",
    "couverts cuillere": "couverts",
    "sculpture verre": "sculpture",
    "vetement pantalon": "vetement",
    "ticket": "ticket",
    "bijou bague chevaliere": "bague",
    "raquette": "raquette",
    "vase cornet": "vase",
    "temps chrono": "chronometre",
    "pot_metallique": "pot",
    "vase potterie archaique": "vase",
    "saxophone": "saxophone",
    "sac cote de maille": "sac_cote_de_maille",
    "cruche verre_metal": "cruche",
    "oeuf porcelaine": "oeuf",
    "vase flacon": "vase",
    "meuble secretaire": "secretaire",
    "seau": "seau",
    "vase alabaster": "vase",
    "sculpture moderne": "sculpture",
    "couverts pelle": "couverts",
    "vetement veste costume_tailleur": "vetement",
    "fauteuil banquette": "fauteuil",
    "bijou bague or_diamant": "bague",
    "meuble buffet": "buffet",
    "meuble bureau secretaire": "bureau",
    "bonbonniere": "bonbonniere",
    "lampadaire abajour": "lampadaire",
    "vetement pilote": "vetement",
    "meuble angle": "meuble_angle",
    "lampe vase": "lampe_vase",
    "table petite rectangle": "table",
    "fauteuil louis-philippe": "fauteuil",
    "plat porcelaine": "plat",
    "plat verre": "plat",
    "lampe moderne moche": "lampe",
    "vase potterie_unie": "vase",
    "vetement militaire": "vetement",
    "chaise bureau": "chaise",
    "vase cong": "vase",
    "vetement top feminin": "vetement",
    "sculpture bois": "sculpture",
    "fauteuil mouton": "fauteuil",
    "couverts ciseaux": "couverts",
    "barometre": "barometre",
    "lampe pied fleuri": "lampe",
    "vetement veste militaire": "vetement",
    "bijou bague medaillon": "bague",
    "vetement robe courte": "vetement",
    "vetement veste autre": "vetement",
    "sculpture plate": "sculpture",
    "medaillon": "medaillon",
    "coupe": "coupe",
    "lampe lalane": "lampe",
    "vase paraplui": "vase",
    "arme blanche dague": "couteau",
    "coupe calice": "coupe",
    "objet ivoire": "objet_ivoire",
    "verre flute": "verre",
    "table demilune": "table",
    "vasque verre": "vasque",
    "vetement manteau court": "vetement",
    "lampe pied sculpte": "lampe",
    "vase rectangle": "vase",
    "fauteuil coussin": "fauteuil",
    "lampe annee70": "lampe",
    "fauteuil moderne": "fauteuil",
    "vetement t-shirt": "vetement",
    "loupe": "loupe",
    "sculpture pierre": "sculpture",
    "sac gucci": "sac",
    "bijou bague alliance": "bague",
    "lampe ballon": "lampe",
    "table violon": "table",
    "table carre": "table"
}