currencies = 'USD|CAD|GBP|CHF|EUR|MAD|JPY|AED|MXN|CZK|PLN'

category = ["montre", "tableau", "plaque", "cuillere", "sculpture",
            "scenes d intérieur","bijoux","boucle d oreille",
            "boucles d oreille","bague",
            "dague","stylo","pendants d oreilles","gourmette",
            "boucles doreille","robe du soir",
            "pendentif","fauteuil", "fourchette", "broderie","aiguiere",
            "legumier","verseuse","laitiere","theiere","portes-couteau",
            "lithographie", "estampe", "serigraphie","broche","medaille",
            "banette","candelabre","chandelier","sauciere",
            "aquarelle", "huile sur toile","huile sur panneau","acrylique",
            "portrait","flambeau","gueridon",
            "rond de serviette", "coquetier","porteclefs",
            "luminaire", "service à", "tirage argentique",
            "argenterie", "photo", "chaise", "table", "amulette",
            "rond de serviette","jatte","bonbonniere",
            "pelle a tarte","portemonnaie","dessous de plat",
            "paniere a pain","coffret", "pince a sucre","seau a champagne",
            "collier", "violon", "couteau", "cierge","gobelet",
            "lampe", "dessin", "gravure", "fusil", "pistolet", "vase ",
            "sucrier", "appliques","insignes","porte-carte",
            "couverts","buffet","encrier","shaker","carafon",
            "verres à pied","cafetière","icône","timbale","timballe",
            "scènes d extérieur",  "affiche","pochoir","présentoir",
            "boite","bouilloire","pendulette","bougeoir",
            "louche","plateau","sautoir","ceinture","plat rond",
            "meuble", "bouteille", "cuiller", "tasse",
            "pièce","moutardier", "salière", "bracelet",
            " sac ","coupe", "canne","alliance","pince a",
            "coupe en cristal","vases ",
            "etui", ]

materiau = ["bois", "bronze", "métal argenté",  "papier",
            "ceramique", "porcelaine", "cuivre","saphir", "rubis",
            "soierie",  "toile", "faïence","pierre", "argent",
            "diamant", "verre"]