services:
  chromadb:
    build: .
    ports:
        - "8000:8000"
    volumes:
        - D:/data/chroma_db/chroma_data:/data/chroma_data
    command: chroma run --path "/data/chroma_data"
    healthcheck: 
        test: curl localhost:8000/api/v1/heartbeat || exit 1
        interval: 100s
        retries: 2
        start_period: 5s
        timeout: 10s