
celery:
  url: "redis://:apasswd@redis:6379/0"

front_end:
  server: 'http://localhost:3000'

product:
  free_plan_days: 7
  initial_closest_volume: 30
  initial_search_volume: 30

plans: 
  free: "free_plan"
  individual: "individual_plan"
  expert: "expert_plan"

email:
  MAIL_SERVER: smtp.gmail.com
  MAIL_PORT: 465
  MAIL_USE_TLS: False
  MAIL_USE_SSL: True