paths:
  root: D:/data
  crawl: ''
  crawl_picture_path: pictures
  crawl_infos_path: infos
  crawl_details_path: details
  crawl_auctions_path: auctions
  crawl_path_new: new
  model: models
  default: default
  artist: artists
  llm: llm_extracts
  features_to_extract: features_to_extract
  llm_extraction: extraction
  picture_training: pictures_training
  text_training: text_training

celery:
  url: "redis://:apasswd@redis:6379/0"

front_end:
  server: 'http://localhost:3000'

product:
  free_plan_days: 7
  initial_closest_volume: 30
  initial_search_volume: 30

plans:
  free: "free_plan"
  individual: "individual_plan"
  expert: "expert_plan"

email:
  MAIL_SERVER: smtp.gmail.com
  MAIL_PORT: 465
  MAIL_USE_TLS: False
  MAIL_USE_SSL: True
