services:
    postgres:
        container_name: postgres
        hostname: db
        build: 
            context: ./
            dockerfile: dockerfile
        ports:
            - 5433:5432
        expose:
            - 5432
        restart: always
        environment:
            - POSTGRES_DB=vectordb
        env_file:
            - ./.env
        volumes:
            - ./init.sql:/tmp/init.sql
            - pgdata:/var/lib/postgresql/data
            - D:/db_backup/vectordb_backup.sql:/tmp/vectordb_dump.sql
            - D:/db_backup/picture_embeddings.csv:/tmp/picture_embeddings.csv
        networks:
            - shared_net

networks:
  shared_net:
    external: true

volumes:
    pgdata: 