services:
    postgres:
        container_name: postgres
        hostname: db
        build:
            context: ./
            dockerfile: dockerfile
        ports:
            - 5433:5432
        expose:
            - 5432
        restart: always
        environment:
            - POSTGRES_DB=vectordb
        env_file:
            - ../global-schemas/.env
        volumes:
            - ./init.sql:/tmp/init.sql
            - pgdata:/var/lib/postgresql/data
        networks:
            - shared_net

networks:
  shared_net:
    external: true

volumes:
    pgdata:

# si pas de memory left, juste prune le cash 20GB free
