FROM postgres:latest

RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    postgresql-server-dev-all \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /tmp
RUN git clone --branch v0.7.2 https://github.com/pgvector/pgvector.git

WORKDIR /tmp/pgvector
RUN make
RUN make install

# Copy the configuration files
# COPY ./pg_hba.conf /etc/postgresql/pg_hba.conf
COPY ./init_db.sh /docker-entrypoint-initdb.d/init_db.sh
# COPY ./postgresql.conf /etc/postgresql/postgresql.conf

# Ensure the script is executable
# RUN chmod +x /docker-entrypoint-initdb.d/init_db.sh

# Ensure proper permissions
# /etc/postgresql/postgresql.conf /etc/postgresql/pg_hba.conf 
# RUN chown -R postgres:postgres /var/lib/postgresql /docker-entrypoint-initdb.d/ 

# Switch to the postgres user for running the PostgreSQL server
# USER postgres

# Start PostgreSQL on port 5433 with custom configuration files
# CMD ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf", "-c", "hba_file=/etc/postgresql/pg_hba.conf", "-c", "port=5433"]
# CMD ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]