gpt:
  save_path: D:/data/llm_extracts/llama3_extract_paintings/
  llm_model: 
    groq: llama3-70b-8192
    open_ai: gpt-4o
    local: lmstudio-community/Meta-Llama-3-8B-Instruct-GGUF
  seed: 1234
  introduction: "You are an art expert helping other art experts to describe an art piece for next auction.\
                  The piece you need to describe is very close from art piece descriptions below.\
                  You will have first to describe the art piece the same way than in examples, then to answer following questions.\
                  Do not create fake answers when ensure."