gpt:
  save_path: D:/data/llm_extracts/llama3_extract_paintings/
  llm_model: 
    groq: llama3-70b-8192
    google: gemini-1.5-flash
    open_ai: gpt-3.5-turbo-0125 #gpt-4o
    local: lmstudio-community/Meta-Llama-3-8B-Instruct-GGUF
  seed: 1234
  temperature: 0.2
  introduction: "You are an art expert who can describe art pieces easily. \
                Below, you have a list of art piece descriptions along with their distances to the final art piece you need to describe. \
                Your role is to write the description of the final art piece in a JSON structured way, both in French and English, based on all the description examples provided. 
                Your description should only include common caracteristics in the list of art piece description. \ 
                Follow these guidelines: \
                - Examples with smaller distances are the closest ones to the final art piece you need to describe. \
                - Do not write any provenance or property information about the art piece. \
                - Exclude any expert reference of object origine, provide only the essential information. \
                - Do not start your answer by Here is the extracted or Response, directly give the JSON output. Make sure all values are quoted."