text_classification:
  ratio_validation : 0.1
  model : 'intfloat/multilingual-e5-large'
  train_batch_size: 8
  test_batch_size: 128
  device : "cuda"
  epochs : 1

  fine_tuned_model : /data/models/multilingual-e5-large_finetuned