FROM python:3.12

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app
COPY . /app

RUN apt-get update &&\
    apt-get install -y apt-utils &&\
    apt-get install -y gcc
    
#Install requirements
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
