FROM python:3.12

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app
COPY . /app

RUN apt-get update &&\
    apt-get install -y apt-utils &&\
    apt-get install -y gcc
    # apt-get install -y wkhtmltopdf  &&\
        # apt-get install --no-install-recommends -y \
        # biber=2.12-2 \
        # latexmk=1:4.61-0.1 \
        # texlive-full=2018.20190227-2
        #rm -rf /var/lib/apt/lists/*

#Install requirements
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
