FROM python:3.12

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update &&\
    apt-get install -y apt-utils

#Install requirements
RUN pip install --upgrade pip
RUN pip install chromadb
