embedding:
  manual_cluster: /data/default/manuel_cluster_mapping_word.json
  device: cuda
  n_top_neighbors: 96
  text_model: 
    text_embeddings_english: 'Alibaba-NLP/gte-large-en-v1.5'
    text_embeddings_french: "dangvantuan/sentence-camembert-large"
  picture_model: /data/models/peft_block23_vit_large_patch14_clip_224_060624_286
  prompt_name : clustering
  prompt:
      text_embeddings_french: "Identifie le type d'objet d'art auquel se réfère la description suivante: "
      text_embeddings_english: "You are an art expert grouping art piece description together: " # do not change !! all embeddings were built with this 
  text:
      batch_size : 64
  picture:
      batch_size : 92
  dim_reduc:
      params:
        umap_n_neighbors : 25
        umap_n_components : 64
  clustering:
    params:
      verbose: 0 #0 or 1 if 1 then plot clusters on projected embeddings
      min_cluster_size: 3 # minimal number of obs for hdbscan clustering
      cluster_selection_epsilon: 2
      n_words_cluster: 5 # number of words to caracterize the cluster
      min_samples : 5 # The number of samples in a neighbourhood for a point to be considered a core point.
