evaluator:
    category_mapping_path: object_category_mapping.json
    info_to_mapping:
        shape_mapping:
            _shape: [_shape]
        country_mapping:
            _country: [_country]
        color_mapping:
            _color: [_color]
        material_mapping:
            vase_material: [vase_material, vase_color]
            painting_support_material: [painting_support_material, painting_material]
        painting_material_mapping:
            painting_material: [painting_material, painting_support_material]
        style_mapping:
            _style: [_periode_or_circa_year, _style"]
        condition_mapping:
            _condition: [_condition]
        decorations_mapping:
            _decorations: [_decorations]
        object_category_mapping:
            object_category: [object_category]

    handle_dates: ["_periode_or_circa_year", "_periode_or_year"]
    handle_cm: ["_height", "_length", "_width"]
    cols_to_float: ["_height", "_diameter", "_length", "_year", "_periode_or_circa_year", "_periode_or_year", "number_described_objects"]
    binary_cols: ["is_signed", "_signed", "is_framed", "is_dated", "is_painted_by_artist"]

    cleaning_mapping:
        period_mapping: {
            "qianlong" : "1780",
            "kangxi": "1692",
            "meiji" : "1886",
            "yongzheng" : "1728",
            "yonghzeng": "1728",
            "jingdezhen": "1540",
            "yuan": "1280",
            "ming": "1500",
            "guangxu" : "1891",
            "tongzhi": "1865",
            "qing" : "1800",
            "tang": "750",
            "song": "1120",
            "sung": "1120",
            "republic": "1930",
            "republique" : "1930",
            "han" : "-220",
            "wanli" : "1600",
            "wan-li" : "1600",
            "jiaqing": "1810",
            "jiajing" : "1540",
            "shunzhi": "1651",
            "daoguang": "1815",
            "xianfeng" : "1845",
            "xuande": "1430",
            "chenghua": "chenghua",
            "restoration": "1815",
            "roman": "100",
            "augustan": "100",
            "edo": "1650",
            "modern": "2000",
            "renaissance": "1600",
            "napoleon iii": "1860",
            "art deco": "1920",
            "medieval": "1200",
            "meissen": "1730",
            "imperial russian" : "1850",
            "nicholas i" : "1830",
            "victorienne": "1870",
            "mid-century": "1950",
            "louis-philippe": "1830",
            "liao": "1000",
            "kadjar": "1790",
            "neolithique": "-4000",
            "basse epoque": "-500",
            "spring and autumn": "-500",
            "hellenistic":  "-300",
            "art nouveau": "1900",
            "louis xvi": "1780",
            "contemporary": "1970",
            "louis xiv": "1680",
            "post-war": "1950",
            "restauration": "1815",
            "neolithic": "-4000"}

        style_mapping: {
            "neolithic": ["neolithic", "prehistoric", "neolithique"],
            "antique_egypt": ["basse epoque", "egypt"],
            "medieval": ["medieval"],
            "zhou": ["zhou", "spring and autumn", "printemps automne"],
            "han" : ["han"],
            "louis-philippe": ["louis-philippe"],
            "asie_centrale_antique": ["liao"],
            "kadjar": ["kadjar"],
            "chine 19": ["chine 19", "china 19", "daoguang", "xianfeng", "jiaqing", "jiajing", "tongzhi", "guangxu"],
            "chine 18": ["chine 18", "china 18", "qianlong", "yonghzeng", "yongzheng", "qing"],
            "chine 16-17": ["chine 16", "china 16", "china 17", "wan-li","wanli", "shunzhi",
                            "jingdezhen", "kangxi"],
            "chine 15": ["xuande", "chenghua"],
            "song" : ["song", "sung"],
            "tang": ["tang"],
            "hellenistic": ["hellenistic", "greece", "helleniste"],
            "antiquite": ["roman", "rome", "antiquite", "augustan"],
            "renaissance": ["renaissance"],
            "napoleon iii": ["napoleon iii", "second empire"],
            "art deco": ["art deco"],
            "art nouveau": ["art nouveau"],
            "empire france": ["restoration", "empire"],
            "imperial russian": ["imperial russian", "nicholas i", "nicholas ii"],
            "victorienne": ["victorienne", "victorian"],
            "daum": ["daum"],
            "meiji": ["meiji", "maiji", "showa"],
            "edo": ["edo"],
            "modern": ["modern"]
        }

        country_mapping: {
            "china" : ["china", "chine", "chinese", "asia", "canton", "asia", "nankin"],
            "france": ["france", "paris", "nancy", "sevre", "limoges"],
            "japan" : ["japan", "japon", "japanese"],
            "italy" : ["italy", "italie", "venice", "sicily"],
            "russia" : ["russia", "russie"],
            "sweden" : ["sweden", "suede"],
            "spain" : ["spain", 'espagne'],
            "tunisia" : ["tunisie", "tunisia"],
            "usa": ["united states", "usa", "american", "southeastern pennsylvania"],
            "austria" : ["austria"],
            "hungary" : ["hungary"],
            "vietnam": ["vietnam", "vietnamese"],
            "egypt": ["egyptian", "egypt"],
            "germany" : ["germany", "berlin", "allemagne"],
            "denmark" : ["denmark", "danemark"],
            "iran" : ["iran", "persia", "perse"],
            "roman": ["roman", "roman empire", "rome", "roma"],
            "greece": ["greece", "attic"],
            "india": ["india"],
            "korea": ["korea"],
            "portugal" : ["portugal"],
            "turkey": ["turkey", "ottoman"],
            "dutch" : ["dutch", "holland"],
            "belgium":["belgium", "belgique"],
            "england" : ["england", "uk"]
        }

        material_mapping: {
            "porcelaine" : ["porcelaine", "porcelain"],
            "ceramique": ["ceramique", "ceramic", "glazed", "glazed ceramic", "ceramics"],
            "emaux": ["emaux", "email", "emaille", "enamel", "enamels", "cloisonne", "enamelled"],
            "gres" : ["gres", "stoneware"],
            "wood": ["wood", "bois", "bamboo", "oak", "chene", "holz", "acajou", "mahagony", "legno"],
            "marble": ["marble", "marbre", "alabaster"],
            "clay" : ["clay", "argile", "barbotine"],
            "agate": ["agate"],
            "bronze" : ["bronze"],
            "aluminum": ["aluminum", "aluminium", "aluchromie"],
            "copper": ["copper", "cuivre"],
            "glass" : ["glass", "verre", "crystal", "cameo", "cristal"],
            "faience": ["fayence", "faience", "maiolica", "majolica"],
            "terre_cuite" : ["biscuit", "earthenware", "terre", "terracotta",
                            "lagynos", "pottery", "poterie", "impasto"],
            "celadon" : ["celadon"],
            "jade": ["jade", "jadeite"],
            "opaline" : ["opal", "opaline"],
            "gold": ["gold", "or"],
            "plastic": ["plastic", "plastique", "plexiglas", "linoleum"],
            "silk": ["silk", "soie"],
            "peau": ["velin", "peau", "skin", "vellum"],
            "   toile   ": ["burlap", "lienzo", "doek", "canvas", "tissu", "toile", "toiles", "tela",
                            "leinwand", "canvasboard", "lin"],
            "ivory": ["ivory", "ivoire"],
            "stone": ["stone", "pierre"],
            "paper": ["scroll", "paper", "papuier", "papier", "arches", "parchemin"],
            "  carton  ": ["millboard", "cartoncino", "card", "cardboard", "carton",
                            "karton", "cartone", "cartonnette", "paperboard"],
            "  panneau  ": ["panneau", "panneaux", "panel", "pane", "board", "isore", "isorel", "hardboard",
                            "masonite", "linen", "linnen", "bois", "wood", "plywood", "contreplaque", "faesite", "hartfaser"],
            "silver": ["silver", "argent"],
            "metal" : ["zinc", "iron", "tole", "metal", "pewter", "tin", "etain", "plomb", "brass", 'laiton', "dinanderie"],
        }

        painting_material_mapping: {
            "   oil   ": ["oil", "oilo", "olio", "peinture", "huile", "olie", "ol", "huiles", "tempera", "oel", "oleo", "olieverf"],
            "paint_spray": ["spray", "aerosol"],
            "gouache": ["gouache", "gouachee"],
            "ink": ["ink", "inks", "encre"],
            "collage": ["collage"],
            " pastel ": ["pastel", "pastello", "pastels"],
            "mixed": ["mixed", "mixe", "mixer", "mixte", "mista"],
            "acrylic": ["acrylic", "acrylique", "acrylics", "acryl"],
            "crayon": ["crayon", "pencil", "fusain"],
            "watercolor": ["aquarel", "acuarela", "aquatinte", "aquarelle", "watercolor", "watercolours", "acquarello", "watercolour", "bodycolour", "acquerello", "aquarell", "aquatint"],
            "serigraphy": ["serigraphy", "serigraphie", "serigraphe", "screenprint", "impression", "screen print"],
            "lithography": ["lithography", "lithograph", "lithographie", "estampe"],
        }

        shape_mapping: {
            "baluster" : ["baluster", "balustre", "baluster form", "baluster jar",
                          "baluster-shaped", "two-handled", "twin-handled"],
            "double gourd": ["double gourd", "gourd-shaped", "gourd", "gourde", "double-gourd"],
            "bottle" : ["bottle", "bouteille"],
            "ovoid": ["ovoid", "oval", "ovoide", "ovoides", "circular", "flattened ovoid", "elongated ovoid",
                      "round", "rounded", "globular", "bulbous", "spherical", "boule", "spherique"],
            "triangular" : ["triangular"],
            "pear shaped": ["pear shaped", "pear shape"],
            "amphora": ["amphora", "amphore", "amphoriskos", "lekythos"],
            "polygonal" : ["hexagonal", "octagonal", "polygonal"],
            "square": ["square", "quadrangulaire", "quadrangular", "rectangular", "square section"],
            "meiping": ["meiping"],
            "rouleau": ["rouleau", "cylindrical", "cylindrique", "barrel"],
            "soliflore" : ["soliflore", "solifleur"],
            "tulip":  ["tulip"],
            "jar": ["jar", "jarre", "urn"],
            "snuff bottle" : ["snuff bottle"],
            "gu": ["gu"],
            "moonflask": ["moonflask", "moon flask"],
            "albarelli" : ["albarelli", "albarello"],
            "cornet" : ["cornet", "conical"],
            "pansu" : ["pansu", "pansue"],
            "piriform": ["piriform", "oblong"],
            "jardiniere": ["jardiniere"],
            "becher": ["beaker", "becher", "cruche", "jug", "carafe"],
            "pot" : ["pots", "pot", "pot a gingembre", "cache pot", "cachepot", "cache-pot"],
            "oviform" : ["medicis", "oviforme", "oviform"],
            "brush pots" : ["brush pots", "brushpot", "brush pot"],
            "hu": ["hu", "hu-shaped"],
            'tripode': ["tripode"],
            "pear-shaped":["pear-shaped"],
            "cong" : ["cong"],
            "potiche" : ["potiche"],
            "egg": ["egg-shaped"],
            "bell" : ["bell-shaped"]
        }

        color_mapping: {
            "multicolor" : ["polychrome", "multi colored", "colored", "multiple",
                            "multicolored", "polychromes", "polychromie", "multicolore",
                            "multi color", "various", "multicolor", "colorful", "varied",
                            "polychrome and gold", "vibrant colors", "vibrant"],
            "blue and white" : ["blue-white", "blue, white", "blue and white",
                                "white and blue", "bleu et blanc", "white blue",
                                "bleu blanc", "white, blue"],
            "blue and green": ["blue and green", "blue-green", "green and blue",
                               "vert et bleu", "bleu et vert", "bluish-green",
                               "blue-green"],
            "blue and gold": ["blue and gold", "gold and blue", "or et bleu", "bleu et or"],
            "red and white": ["red and white", "white and red", "bland et rouge",
                              "rouge et blanc", "black, rouge", "rouge, blanc",
                              "white, red", "red, white"],
            "iridescent": ["iridescent", "opalescent"],
            "green" : ["floral", "green", "vert", "olive green", "famille verte", "greenish"],
            "white": ["white", "blanc", "blanche"],
            "blue" : ["blue", "bleu", "cobalt blue", "pale blue", "dark blue", "indigo", "aquamarine"],
            "yellow" : ["yellow", "yellow and orange", "flamed", "flame"],
            "amber": ["amber and white", "amber"],
            "turquoise": ["turquoise", "blue turquoise"],
            "red": ['reddish',"rouge", "red", "iron red", "sang de boeuf", "copper-red", "blood", "oxblood", "burgundy"],
            "vert_pale" : ["celadon", "vert pale", "pale green"],
            "brown": ["brownish", "wood",  "brown", "earthy", "earth", "brownish black", "marron", "dark brown", "beige and brown", "bronze"],
            "black": ["black", "noir", "noire", "black and gold", "dark"],
            "orange" : ["orange", "copper", "caramel", "peach", 'coral', "salmon"],
            "transparent" : ["transparent", "colorless", "translucent"],
            "purple": ["purple", "mauve", "violet", "aubergine", "lavender", "lilac", "prune"],
            "rose": ["rose", "pink", "ochre"],
            "gold": ["gold", "gilt", "or", "golden"],
            "ocre": ["ocre", terracotta],
            "beige" : ["beige", "creme", "clear", "cream", "ivory", "patinated", "soft", 'bright', "opalin"],
            "silver" : ["silver", "argent"],
            "grey": ["grey", "gris", "gray"]
        }

        manufacturer_mapping: {
            "meissen" : ["meissen"],
            "daum" : ["daum"],
            "sevres": ["sevres"],
            "tiffany": ["tiffany"],
            "lalique": ["lalique"],
            "madoura" : ["madoura"],
            "longwy" : ["longwy"],
            "boch keramis" : ["boch"],
            "galle" : ["galle"],
            "limoges" : ["limoges"],
            "murano" : ["murano"],
            "paris" : ["paris", "made in france", "le verre francais"],
            "royal worcester" : ["royal worcester"],
            "baccarat" : ["baccarat"],
            "keramis" : ["keramis"],
            "workshops beijing": ["workshops beijing"],
            "leerdam": ["leerdam"],
            "vallauris" : ["vallauris"],
            "pantin" : ["pantin"]
        }

        condition_mapping: {
            "very_good" : ["very good", "excellent", "exquisite", "perfect", "parfait"],
            "good_" : ["good", "restored", "restorations", "fine", "repaired", "bon", "minor", "restaurations", "restauration"],
            "okay_": ["old wear", "small signs", "minimally damaged", "some egrenures", "some wear", "some chips", "signs of use", "used",
                    "slightly", "small chips", "minor defects", "usures", "minor", "craquelures", "manques", "craquele"],
            "poor" : ["craquelee", "craquelure", "cracks", "damaged", "dechirure", "manques", "degraded", "cracked", "accidents", "taches", "accident", "worn", "damages", "fractured", "chipped", "crack", "eclat"],
        }

        decorations_mapping: {
            "landscape_nature": ["floral", "flowers", "branches", "foliage", "nature", "birds",
                    "poppy", "landscape", "water", "vegetal", "butterflies", "lilies", "clouds", "wind", "rain"],
            "dragons" : ["dragons"],
            "human": ["palaces", "life", "people", "human", "faces", "figures"],
            "painted": ["hand-painted", "painted"],
            "uniforme": ["crackled glaze", "partially glazed"],
            "color": ["polychrome decoration", "colorful"],
            "glass": ["glass", "transparent"],
            "patterns" : ["blue and white", "designs", "patterns", "intricate", "geometric", "abstract", "traditional chinese motifs"]
        }
