picture_classification:
  ratio_validation : 0.15
  model : vit_large_patch14_clip_224.openai_ft_in12k_in1k
  train_batch_size: 64
  test_batch_size: 128
  device : "cuda"
  epochs : 5
  default_image_path: MISSING.jpg
  fine_tuned_model_path : peft_block23_vit_large_patch14_clip_224_280416
