crawling:
    tor_config:
        SocksPort : 9050
        EntryNodes : '{FR},{ES},{IT},{DE}'
        ExitNodes : '{FR},{ES},{PT},{IT},{DE},{UK},{BE},{SW}'
        CookieAuthentication : '1'
        MaxCircuitDirtiness : '600'
    root_path: D:/data
    path_new: new
    picture_path: pictures
    infos_path: infos
    details_path: details
    auctions_path: auctions
    met:
        webpage_url : https://www.metmuseum.org
        url_path : D:/data/met/infos/MetObjects.csv
        save_picture_path : D:/data/met/pictures
        save_data_path : D:/data/met/
        settings : 
            browser : chrome 
            nodes : 1
            retry : 1
    drouot: # 3.3M
        history_start_year: 2000
        webpage_url : https://www.gazette-drouot.com/recherche/lot/
        auctions_url : https://www.gazette-drouot.com/ventes-aux-encheres/passees?isForAgenda=true&typeName=passees
        auctions:
            liste_elements : 
                by_type: CLASS_NAME
                value_css: infosVente
            per_element:
                AUCTION_TITLE:
                    by_type: CLASS_NAME
                    value_css: nomVente
                DATE: 
                    by_type: CLASS_NAME
                    value_css: capitalize-fl
                TYPE_SALE:
                    by_type: CLASS_NAME
                    value_css: typeVente-fl
                PLACE:
                    by_type: CLASS_NAME
                    value_css: lieuVente
                HOUSE:
                    by_type: CLASS_NAME
                    value_css: etudeVente
        items:
            functions:
                - 'self.scrowl_driver(driver, Y=200)'
            global_element:
                DATE:
                    by_type: CLASS_NAME
                    value_css: capitalize-fl
                TYPE_SALE:
                    by_type: CLASS_NAME
                    value_css: typeOnline
                AUCTION_TITLE:
                    by_type: CLASS_NAME
                    value_css: nomVente
                PLACE:
                    by_type: CLASS_NAME
                    value_css: lieuVente
                HOUSE:
                    by_type: CLASS_NAME
                    value_css: etudeVente
            liste_elements : 
                by_type: CLASS_NAME
                value_css: Lot
            per_element:
                LOT_NUMBER:
                    by_type: CLASS_NAME
                    value_css: lotNumListe
                    replace: 
                        - "Lot n° "
                        - ""
                ITEM_TITLE:
                    by_type: CLASS_NAME
                    value_css: lotArtisteListe
                ITEM_INFOS:
                    by_type: CLASS_NAME
                    value_css: lotDescriptionListe
                RESULT:
                    by_type: CLASS_NAME
                    value_css: lotResulatListe
                ESTIMATE:
                    by_type: CLASS_NAME
                    value_css: lotEstimationListe
                URL_FULL_DETAIL:
                    by_type: TAG_NAME
                    value_css: a
                    attribute: href
                URL_PICTURE:
                    by_type: CLASS_NAME
                    value_css: imgLot
                    value_of_css_element: background-image
        detailed: 
            per_element : 
                URL_AUCTION:
                    by_type : CLASS_NAME
                    value_css : breadcumTitreVente
                    attribute: href
                TITLE:
                    by_type : CLASS_NAME
                    value_css : lotArtisteFiche
                DETAIL:
                    by_type : XPATH
                    value_css : //div[@class='lotDescriptionFiche']/h2
                URL_PICTURE:
                    liste_elements : 
                        by_type: CLASS_NAME
                        value_css: thumbPreview
                    per_element : 
                        value_of_css_element: background
        pictures:
            global_element: 
                URL_PICTURE_CANVAS:
                    by_type: TAG_NAME
                    value_css: canvas
                    is_canvas: True
    christies: # 2M
        history_start_year: 1999
        webpage_url : https://www.christies.com/en/auction/
        auctions_url : https://www.christies.com/en/results?language=en& #month=3&year=2024
        correction_urls_auction : D:/data/christies/auctions/correction_urls_auctions.pickle
        auctions:
            crawler_infos:
                url_sleep: 1
                is_picture: True
                is_cookie: True
                is_javascript: True
            functions:
                - "self.handle_click_element(driver, 'CLASS_NAME', 'banner-actions-container', 'ID', 'onetrust-reject-all-handler')" # cookie
                - "self.handle_click_element(driver, 'CLASS_NAME', 'fsu--wrapper', 'CLASS_NAME', 'closeiframe')" # signup
                - 'self.scrowl_driver(driver, Y=150)'
            liste_elements : 
                by_type: XPATH
                value_css: '//ul[@aria-labelledby="calendar-tab-undefined"]/li'
            per_element:
                URL_AUCTION:
                    by_type : CLASS_NAME
                    value_css : chr-event-tile__title
                    attribute: href
                AUCTION_TITLE:
                    by_type : CLASS_NAME
                    value_css : chr-event-tile__title
                LOCALISATION:
                    by_type : CLASS_NAME
                    value_css : chr-label-s
        items:
            crawler_infos:
                url_sleep: 0.5
                is_picture: False
                is_cookie: True
                is_javascript: True
            functions:
                - "self.handle_click_element(driver, 'CLASS_NAME', 'banner-actions-container', 'ID', 'onetrust-reject-all-handler')" # cookie
                - "self.handle_click_element(driver, 'CLASS_NAME', 'fsu--wrapper', 'CLASS_NAME', 'closeiframe')" # signup
                - 'self.scrowl_driver(driver, Y=150)'
            liste_elements : 
                by_type: XPATH
                value_css: //div[@class='container-fluid']/ul/li
            per_element:
                URL_FULL_DETAIL:
                    by_type: CLASS_NAME
                    value_css: chr-lot-tile__link
                    attribute: href
                LOT:
                    by_type: CLASS_NAME
                    value_css: chr-lot-tile__content-header
                ITEM_INFOS:
                    by_type: CLASS_NAME
                    value_css: chr-lot-tile__content
                ESTIMATE:
                    by_type: CLASS_NAME
                    value_css: chr-lot-tile__price-value
                RESULT:
                    by_type: CLASS_NAME
                    value_css: chr-lot-tile__dynamic-price
        detailed : 
            crawler_infos:
                url_sleep: 0.2
                is_picture: True
                is_cookie: True
                is_javascript: True
            functions:
                - "self.handle_click_element(driver, 'CLASS_NAME', 'banner-actions-container', 'ID', 'onetrust-reject-all-handler')" # cookie
                - "self.handle_click_element(driver, 'CLASS_NAME', 'fsu--wrapper', 'CLASS_NAME', 'closeiframe')" # signup
            per_element : 
                URL_AUCTION:
                    by_type: CLASS_NAME
                    value_css: chr-breadcrumb__link 
                    attribute: href
                ARTIST:
                    by_type : CLASS_NAME
                    value_css : chr-lot-header__artist-name
                TITLE:
                    by_type : CLASS_NAME
                    value_css : chr-lot-header__title
                DETAIL:
                    by_type : CLASS_NAME
                    value_css: chr-accordion
                URL_PICTURE:
                    functions:
                        - "self.click_element(driver, 'CLASS_NAME', 'chr-lot-header__image-container')"
                    liste_elements : 
                        by_type: CLASS_NAME
                        value_css: chr-gallery__slide
                    per_element : 
                        by_type: TAG_NAME
                        value_css: img
                        attribute: src
    sothebys: # 0.8M
        history_start_year: 2007
        webpage_url : https://www.sothebys.com/en/buy/auction
        auctions_url : https://www.sothebys.com/en/results? #6581
        auctions:
            liste_elements : 
                by_type: CLASS_NAME
                value_css: SearchModule-results-item
            per_element:
                URL_AUCTION:
                    by_type : CLASS_NAME
                    value_css : Card-info-container
                    attribute: href
                AUCTION_TITLE:
                    by_type : CLASS_NAME
                    value_css : Card-title
                DATE:
                    by_type : CLASS_NAME
                    value_css : Card-details
                TYPE_SALE:
                    by_type : CLASS_NAME
                    value_css : Card-category
        items: 
            crawler_infos:
                url_sleep: 1.5
                is_picture: False
                is_cookie: True
                is_javascript: True
            buy_url:
                global_element:
                    DATE:
                        by_type: CLASS_NAME
                        value_css: css-19ct9dd
                    AUCTION_TITLE:
                        by_type: XPATH
                        value_css: //h1[@data-testid='header-desktop']
                liste_elements : 
                    by_type: XPATH
                    value_css: //div[@aria-label='List of lots']/div/div
                per_element:
                    URL_FULL_DETAIL:
                        by_type: TAG_NAME
                        value_css: a
                        attribute: href
                    ITEM_TITLE:
                        by_type: XPATH
                        value_css: a/div/div[2]/div/div[1]
                    RESULT:
                        by_type: XPATH
                        value_css: a/div/div[2]/div/span[2]
                    ESTIMATE:
                        by_type: XPATH
                        value_css: a/div/div[2]/div/span[1]
            auctions_url:
                global_element:
                    DATE:
                        by_type: CLASS_NAME
                        value_css: AuctionsModule-auction-info
                    AUCTION_TITLE:
                        by_type: CLASS_NAME
                        value_css: AuctionsModule-auction-title
                liste_elements : 
                    by_type: CLASS_NAME
                    value_css: AuctionsModule-results-item
                per_element:
                    URL_FULL_DETAIL:
                        by_type: TAG_NAME
                        value_css: a
                        attribute: href
                    ITEM_TITLE:
                        by_type: CLASS_NAME
                        value_css: title
                    ITEM_INFOS:
                        by_type: CLASS_NAME
                        value_css: description
                    RESULT:
                        by_type: CLASS_NAME
                        value_css: info
                    ESTIMATE:
                        by_type: CLASS_NAME
                        value_css: estimate
        detailed : 
            buy_url:
                per_element : 
                    TITLE:
                        by_type: CLASS_NAME
                        value_css: css-542wex
                    URL_AUCTION: 
                        by_type: XPATH
                        value_css: //div[@class='css-2v1h2i']/nav/span
                        attribute: href
                    DETAIL:
                        by_type : ID
                        value_css : "LotDetails"
                    URL_PICTURE:
                        liste_elements : 
                            by_type: XPATH
                            value_css: //ul[@class='slider animated']/li
                        per_element : 
                            by_type: TAG_NAME
                            value_css: img
                            attribute: srcset
            auctions_url:
                per_element : 
                    URL_AUCTION: 
                        by_type: XPATH
                        value_css: //div[@class='LotPage-breadcrumbs-breadcrumb']/a
                        attribute: href
                    DETAIL:
                        by_type : CLASS_NAME
                        value_css : LotPage-details
                    URL_PICTURE:
                        by_type: XPATH
                        value_css: //div[@class='VerticalNavGallerySlide-mediaContent']/picture/img
                        attribute: srcset
    millon: # 0.2M
        history_start_year: 2012
        webpage_url: https://www.millon.com/catalogue/ventes-passees/
        auctions_url: https://www.millon.com/catalogue/ventes-passees/
        auctions:
            liste_elements: 
                by_type: CLASS_NAME
                value_css: item
            per_element:
                URL_AUCTION:
                    by_type : CLASS_NAME
                    value_css : card-image
                    attribute: href
                AUCTION_TITLE:
                    by_type : CLASS_NAME
                    value_css : card-title
                LOCALISATION:
                    by_type : CLASS_NAME
                    value_css : selling-location
                AUCTION_DATE:
                    by_type: CLASS_NAME
                    value_css: day-of-sale
                AUCTION_HOUR:
                    by_type: CLASS_NAME
                    value_css: sales-time
        items:
            liste_elements: 
                by_type: CLASS_NAME
                value_css: item
            per_element:
                ITEM_TITLE:
                    by_type: CLASS_NAME
                    value_css: card-title
                URL_FULL_DETAIL:
                    by_type : CLASS_NAME
                    value_css : card-image
                    attribute: href
                LOT:
                    by_type: CLASS_NAME
                    value_css: lot
                ITEM_INFOS:
                    by_type: CLASS_NAME
                    value_css: content
                FINAL_RESULT:
                    by_type: CLASS_NAME
                    value_css: estimation
        detailed: 
            per_element : 
                AUCTION_DATE:
                    by_type: CLASS_NAME
                    value_css: sale--info
                AUCTION_TITLE:
                    by_type: XPATH
                    value_css: //p[@class='sale--info']/a
                ESTIMATE:
                    by_type: CLASS_NAME
                    value_css: box-estimation
                RESULT:
                    by_type: CLASS_NAME
                    value_css: box-awarded
                TITLE:
                    by_type : CLASS_NAME
                    value_css : wrap-title
                DETAIL:
                    by_type : XPATH
                    value_css : //div[@class='detail']/div[1]
                URL_PICTURE:
                    liste_elements : 
                        by_type: XPATH
                        value_css: //div[@class='slider__bottom slick-slider']/div
                    per_element : 
                        by_type: TAG_NAME
                        value_css: img
                        attribute: src
    bonhams: # 2M
        auctions_url: https://www.bonhams.com/fr/auctions/results/
    artcurial: #TODO:
        auctions_url: https://www.artcurial.com/resultats-ventes-aux-encheres
    artus: # TODO 2003-2024 - merdique vend de l'industriel ...
        history_start_year: 2003
        webpage_url : https://www.artus-encheres.fr/ventes-passees
        auctions_url: https://www.artus-encheres.fr/ventes-passees
    agutes: # TODO: 2003-2024
        auctions_url: https://www.aguttes.com/resultats-des-ventes
    tajan:
        auctions_url: https://www.tajan.com/fr/past/?pg=1
    ivoire:
        auctions_url: https://www.ivoire-france.com/chartres/fr/resultats/59-resultats_ventes
    liladam:
        auctions_url: https://www.liladam.com/ventes-passees
    rossini: 
        auctions_url: https://www.rossini.fr/resultats
    orsenat: 
        auctions_url: https://www.osenat.com/resultats-ventes-passees
    sgl-encheres:
        auctions_url: https://www.sgl-encheres.com/ventes-passees
    ader:
        auctions_url: https://www.ader-paris.fr/ventes-passees