server:
  host: host.docker.internal #postgres #
  database: vectordb
  port: 5433

email:
  MAIL_SERVER: smtp.gmail.com
  MAIL_PORT: 465
  MAIL_USE_TLS: False
  MAIL_USE_SSL: True

celery:
  url: "redis://:apasswd@redis:6379/0"

front_end:
  server: 'http://localhost:3000'