services:
  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.init
    restart: always
    depends_on:
      - airflow-init
      - airflow-postgres
    env_file:
      - ../global-schemas/.env
    environment:
      - ROOT_PATH=/opt/airflow/data
    volumes:
      - D:/data:/opt/airflow/data
      - ../global-schemas/configs/:/opt/airflow/configs
      - ../global-schemas/src/:/opt/airflow/src
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: >
      bash -c "
      airflow db upgrade &&
      airflow webserver
      "
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/webserver_config.py ] && curl --fail http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - shared_net

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.init
    restart: always
    depends_on:
      - airflow-init
      - airflow-postgres
    env_file:
      - ../global-schemas/.env
    environment:
      - ROOT_PATH=/opt/airflow/data
    volumes:
      - D:/data:/opt/airflow/data
      - ../global-schemas/configs/:/opt/airflow/configs
      - ../global-schemas/src/:/opt/airflow/src
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: >
      bash -c "
      airflow db upgrade &&
      airflow scheduler
      "
    networks:
      - shared_net

  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile.init
    restart: on-failure
    env_file:
      - ../global-schemas/.env
    environment:
      - ROOT_PATH=/opt/airflow/data
    volumes:
      - D:/data:/opt/airflow/data
      - ../global-schemas/configs/:/opt/airflow/configs
      - ../global-schemas/src/:/opt/airflow/src
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    networks:
      - shared_net

  airflow-postgres:
    image: postgres:13
    env_file:
      - ../global-schemas/.env
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    networks:
      - shared_net

volumes:
  postgres-db-volume:

networks:
  shared_net:
    external: true
