crawling:
    met:
        webpage_url : https://www.metmuseum.org
        url_path : ./data/openaccess/MetObjects.csv
        save_picture_path : ./data/openaccess/pictures
        save_data_path : ./data/openaccess/
        settings : 
            browser : chrome 
            nodes : 1
            retry : 1
    drouot: 
        webpage_url : https://www.gazette-drouot.com/recherche/lot/
        url_path : ./data/drouot/infos/*
        save_picture_path : ./data/drouot/pictures
        save_data_path : ./data/drouot/infos
        settings : 
            browser : chrome 
            nodes : 1
            retry : 1   
    chrystys: 
        webpage_url : https://www.christies.com/en/search?
        url_path : ./data/chrystys/infos/*
        save_picture_path : ./data/chrystys/pictures
        save_data_path : ./data/chrystys/infos
        settings : 
            browser : chrome 
            nodes : 1
            retry : 1   