crawling:
    met:
        webpage_url : https://www.metmuseum.org
        url_path : ./data/met/infos/MetObjects.csv
        save_picture_path : ./data/met/pictures
        save_data_path : ./data/met/
        settings : 
            browser : chrome 
            nodes : 1
            retry : 1
    drouot: 
        webpage_url : https://www.gazette-drouot.com/recherche/lot/
        auctions_url : https://www.gazette-drouot.com/ventes-aux-encheres/passees?
        url_crawled : https://www.gazette-drouot.com/ventes-aux-encheres/
        url_path : ./data/drouot/infos/*
        save_picture_path : ./data/drouot/pictures
        save_data_path : ./data/drouot/infos
        save_data_path_auctions: ./data/drouot/auctions
        save_data_path_details: ./data/drouot/details
        settings : 
            browser : chrome 
            nodes : 1
            retry : 1   
        auctions:
            liste_elements : 
                by_type: CLASS_NAME
                value_css: infosVente
            per_element:
                AUCTION_TITLE:
                    by_type: CLASS_NAME
                    value_css: nomVente
                DATE: 
                    by_type: CLASS_NAME
                    value_css: capitalize-fl
                TYPE_SALE:
                    by_type: CLASS_NAME
                    value_css: typeVente-fl
                PLACE:
                    by_type: CLASS_NAME
                    value_css: lieuVente
                HOUSE:
                    by_type: CLASS_NAME
                    value_css: etudeVente
        items:
            liste_elements : 
                by_type: CLASS_NAME
                value_css: Lot
            per_element:
                DATE:
                    by_type: CLASS_NAME
                    value_css: capitalize-fl
                TYPE_SALE:
                    by_type: CLASS_NAME
                    value_css: typeOnline
                AUCTION_TITLE:
                    by_type: CLASS_NAME
                    value_css: nomVente
                PLACE:
                    by_type: CLASS_NAME
                    value_css: lieuVente
                HOUSE:
                    by_type: CLASS_NAME
                    value_css: etudeVente
                LOT_NUMBER:
                    by_type: CLASS_NAME
                    value_css: lotNumListe
                    replace: 
                        - "Lot n° "
                        - ""
                ITEM_TITLE:
                    by_type: CLASS_NAME
                    value_css: lotArtisteListe
                ITEM_INFOS:
                    by_type: CLASS_NAME
                    value_css: lotDescriptionListe
                RESULT:
                    by_type: CLASS_NAME
                    value_css: lotResulatListe
                ESTIMATE:
                    by_type: CLASS_NAME
                    value_css: lotEstimationListe
                URL_FULL_DETAIL:
                    by_type: TAG_NAME
                    value_css: a
                    attribute: href
        detailed : 
            per_element : 
                ARTIST:
                    by_type : CLASS_NAME
                    value_css : info_tps-prix-online
                TITLE:
                    by_type : CLASS_NAME
                    value_css : litzt600
                DETAIL:
                    by_type : CLASS_NAME
                    value_css : descriptionLineWrap
    christies: 
        webpage_url : https://www.christies.com/en/auction/
        auctions_url : https://www.christies.com/en/results?language=en& #month=3&year=2024
        url_path : ./data/christies/infos/*
        save_picture_path : ./data/christies/pictures
        save_data_path : ./data/christies/infos
        save_data_path_auctions: ./data/christies/auctions
        save_data_path_details: ./data/christies/details
        correction_urls_auction : ./data/christies/auctions/correction_urls_auctions.pickle
        settings : 
            browser : chrome 
            nodes : 1
            retry : 1 
        auctions:
            functions:
                - 'self.scrowl_driver(driver, Y=150)'
                - 'self.handle_signups(driver)'
            liste_elements : 
                by_type: XPATH
                value_css: '//ul[@aria-labelledby="calendar-tab-undefined"]/li'
            per_element:
                URL_AUCTION:
                    by_type : CLASS_NAME
                    value_css : chr-event-tile__title
                AUCTION_TITLE:
                    by_type : CLASS_NAME
                    value_css : chr-event-tile__title
                LOCALISATION:
                    by_type : CLASS_NAME
                    value_css : chr-label-s
        items:
            liste_elements : 
                by_type: CLASS_NAME
                value_css: chr-browse-lot-tile-wrapper
            per_element:
                URL_FULL_DETAIL:
                    by_type: CLASS_NAME
                    value_css: chr-lot-tile__link
                    attribute: href
                LOT:
                    by_type: CLASS_NAME
                    value_css: chr-lot-tile__content-header
                ITEM_INFOS:
                    by_type: CLASS_NAME
                    value_css: chr-lot-tile__content
                ESTIMATE:
                    by_type: CLASS_NAME
                    value_css: chr-lot-tile__price-value
                RESULT:
                    by_type: CLASS_NAME
                    value_css: chr-lot-tile__dynamic-price
                URL_PICTURE:
                    by_type: TAG_NAME
                    value_css: img
                    attribute: src
                    split:
                        character: "?"
                        id_split: 0
        detailed : 
            per_element : 
                ARTIST:
                    by_type : CLASS_NAME
                    value_css : chr-lot-header__artist-name
                TITLE:
                    by_type : CLASS_NAME
                    value_css : chr-lot-header__title
                DETAIL:
                    by_type : CLASS_NAME
                    value_css : chr-lot-section__accordion--text
    sothebys: 
        webpage_url : https://www.sothebys.com/en/buy/auction
        auctions_url : https://www.sothebys.com/en/results? #6581
        url_crawled :  https://rmsothebys.com/en/home/auction-results/
        url_path : ./data/sothebys/infos/*
        save_picture_path : ./data/sothebys/pictures
        save_data_path : ./data/sothebys/infos
        save_data_path_auctions: ./data/sothebys/auctions
        save_data_path_details: ./data/sothebys/details
        oldest_year : 2007
        settings : 
            browser : chrome 
            nodes : 1
            retry : 1 
        auctions:
            liste_elements : 
                by_type: CLASS_NAME
                value_css: SearchModule-results-item
            per_element:
                URL_AUCTION:
                    by_type : CLASS_NAME
                    value_css : Card-info-container
                    attribute: href
                AUCTION_TITLE:
                    by_type : CLASS_NAME
                    value_css : Card-title
                DATE:
                    by_type : CLASS_NAME
                    value_css : Card-details
                TYPE_SALE:
                    by_type : CLASS_NAME
                    value_css : Card-category
        items:
            buy_url:
                liste_elements : 
                    by_type: XPATH
                    value_css: //div[@aria-label='List of lots']/div/div
                per_element:
                    DATE:
                        by_type : CLASS_NAME
                        value_css : css-1bnt3nz
                    URL_FULL_DETAIL:
                        by_type: CLASS_NAME
                        value_css: css-1ivophs
                        attribute: href
                    BRUT_RESULT:
                        by_type: TAG_NAME
                        value_css: span
                    URL_PICTURE:
                        by_type: TAG_NAME
                        value_css: img
                        attribute: src
                        replace:
                            - "extra_small"
                            - "small"
            auctions_url:
                liste_elements : 
                    by_type: CLASS_NAME
                    value_css: AuctionsModule-results-item
                per_element:
                    DATE:
                        by_type : CLASS_NAME
                        value_css : AuctionsModule-auction-info
                    URL_FULL_DETAIL:
                        by_type: XPATH
                        value_css: //div[@class='image']/a
                        attribute: href
                    ITEM_TITLE:
                        by_type: CLASS_NAME
                        value_css: title
                    ITEM_INFOS:
                        by_type: CLASS_NAME
                        value_css: description
                    BRUT_RESULT:
                        by_type: CLASS_NAME
                        value_css: estimate
                    URL_PICTURE:
                        by_type: TAG_NAME
                        value_css: img
                        attribute: src
                        replace:
                            - "extra_small"
                            - "small"
        detailed : 
            per_element : 
                ARTIST:
                    by_type : CLASS_NAME
                    value_css : LotPage-artistName
                TITLE:
                    by_type : CLASS_NAME
                    value_css : LotPage-pieceTitle
                DETAIL:
                    by_type : CLASS_NAME
                    value_css : LotPage-lotDetails  
                CONDITION:
                    by_type : CLASS_NAME
                    value_css : LotPage-lotDescription
                NOTE_CATALOGUE :
                    by_type: CLASS_NAME
                    value_css : LotPage-lotDescription 