crawling:
    met:
        webpage_url : https://www.metmuseum.org
        url_path : ./data/openaccess/MetObjects.csv
        save_picture_path : ./data/openaccess/pictures
        save_data_path : ./data/openaccess/
        settings : 
            browser : chrome 
            nodes : 1
            retry : 1
    drouot: 
        webpage_url : https://www.gazette-drouot.com/recherche/lot/
        auctions_url : https://www.gazette-drouot.com/ventes-aux-encheres/passees?
        url_path : ./data/drouot/infos/*
        save_picture_path : ./data/drouot/pictures
        save_data_path : ./data/drouot/infos
        save_data_path_auctions: ./data/drouot/auctions
        settings : 
            browser : chrome 
            nodes : 1
            retry : 1   
    christies: 
        webpage_url : https://www.christies.com/en/auction/
        auctions_url : https://www.christies.com/en/results?language=en& #month=3&year=2024
        url_path : ./data/christies/infos/*
        save_picture_path : ./data/christies/pictures
        save_data_path : ./data/christies/infos
        save_data_path_auctions: ./data/christies/auctions
        settings : 
            browser : chrome 
            nodes : 1
            retry : 1   