crawling:
    met:
        webpage_url : https://www.metmuseum.org
        url_path : ./data/met/infos/MetObjects.csv
        save_picture_path : ./data/met/pictures
        save_data_path : ./data/met/
        settings : 
            browser : chrome 
            nodes : 1
            retry : 1
    drouot: 
        webpage_url : https://www.gazette-drouot.com/recherche/lot/
        auctions_url : https://www.gazette-drouot.com/ventes-aux-encheres/passees?
        url_crawled : https://www.gazette-drouot.com/ventes-aux-encheres/
        url_path : ./data/drouot/infos/*
        save_picture_path : ./data/drouot/pictures
        save_data_path : ./data/drouot/infos
        save_data_path_auctions: ./data/drouot/auctions
        save_data_path_details: ./data/drouot/details
        settings : 
            browser : chrome 
            nodes : 1
            retry : 1   
        auctions:
            liste_elements : 
                by_type: CLASS_NAME
                value_css: infosVente
            per_element:
                AUCTION_TITLE:
                    by_type: CLASS_NAME
                    value_css: nomVente
                DATE: 
                    by_type: CLASS_NAME
                    value_css: capitalize-fl
                TYPE_SALE:
                    by_type: CLASS_NAME
                    value_css: typeVente-fl
                PLACE:
                    by_type: CLASS_NAME
                    value_css: lieuVente
                HOUSE:
                    by_type: CLASS_NAME
                    value_css: etudeVente
        items:
            liste_elements : 
                by_type: CLASS_NAME
                value_css: Lot
            per_element:
                DATE:
                    by_type: CLASS_NAME
                    value_css: capitalize-fl
                TYPE_SALE:
                    by_type: CLASS_NAME
                    value_css: typeOnline
                AUCTION_TITLE:
                    by_type: CLASS_NAME
                    value_css: nomVente
                PLACE:
                    by_type: CLASS_NAME
                    value_css: lieuVente
                HOUSE:
                    by_type: CLASS_NAME
                    value_css: etudeVente
                LOT_NUMBER:
                    by_type: CLASS_NAME
                    value_css: lotNumListe
                    replace: 
                        - "Lot n° "
                        - ""
                ITEM_TITLE:
                    by_type: CLASS_NAME
                    value_css: lotArtisteListe
                ITEM_INFOS:
                    by_type: CLASS_NAME
                    value_css: lotDescriptionListe
                RESULT:
                    by_type: CLASS_NAME
                    value_css: lotResulatListe
                ESTIMATE:
                    by_type: CLASS_NAME
                    value_css: lotEstimationListe
                URL_FULL_DETAIL:
                    by_type: TAG_NAME
                    value_css: a
                    attribute: href
        detailed : 
            per_element : 
                ARTIST:
                    by_type : CLASS_NAME
                    value_css : info_tps-prix-online
                TITLE:
                    by_type : CLASS_NAME
                    value_css : litzt600
                DETAIL:
                    by_type : CLASS_NAME
                    value_css : descriptionLineWrap
    christies: 
        webpage_url : https://www.christies.com/en/auction/
        auctions_url : https://www.christies.com/en/results?language=en& #month=3&year=2024
        url_path : ./data/christies/infos/*
        save_picture_path : ./data/christies/pictures
        save_data_path : ./data/christies/infos
        save_data_path_auctions: ./data/christies/auctions
        save_data_path_details: ./data/christies/details
        correction_urls_auction : ./data/christies/auctions/correction_urls_auctions.pickle
        settings : 
            browser : chrome 
            nodes : 1
            retry : 1   
        detailed : 
            per_element : 
                ARTIST:
                    by_type : CLASS_NAME
                    value_css : chr-lot-header__artist-name
                TITLE:
                    by_type : CLASS_NAME
                    value_css : chr-lot-header__title
                DETAIL:
                    by_type : CLASS_NAME
                    value_css : chr-lot-section__accordion--text
    sothebys: 
        webpage_url : https://www.sothebys.com/en/buy/auction
        auctions_url : https://www.sothebys.com/en/results? #6581
        url_crawled :  https://rmsothebys.com/en/home/auction-results/
        url_path : ./data/sothebys/infos/*
        save_picture_path : ./data/sothebys/pictures
        save_data_path : ./data/sothebys/infos
        save_data_path_auctions: ./data/sothebys/auctions
        save_data_path_details: ./data/sothebys/details
        oldest_year : 2007
        settings : 
            browser : chrome 
            nodes : 1
            retry : 1 
        detailed : 
            per_element : 
                ARTIST:
                    by_type : CLASS_NAME
                    value_css : LotPage-artistName
                TITLE:
                    by_type : CLASS_NAME
                    value_css : LotPage-pieceTitle
                DETAIL:
                    by_type : CLASS_NAME
                    value_css : LotPage-lotDetails  
                CONDITION:
                    by_type : CLASS_NAME
                    value_css : LotPage-lotDescription
                NOTE_CATALOGUE :
                    by_type: CLASS_NAME
                    value_css : LotPage-lotDescription 