flat_file:
  insee:
    carreaux_200m:  # https://www.insee.fr/fr/statistiques/7655475?sommaire=7655515
      met : 
        path : ./data/insee/200m/carreaux_200m_met.csv
        sep: ","
      mart : 
        path : ./data/insee/200m/carreaux_200m_mart.csv
        sep : ","
      reun : 
        path: ./data/insee/200m/carreaux_200m_reun.csv
        sep : ","
    carreaux_1km: 
      met : 
        path: ./data/insee/km/carreaux_1km_met.csv
        sep : ","
      mart : 
        path: ./data/insee/km/carreaux_1km_mart.csv
        sep : ","
      reun : 
        path: ./data/insee/km/carreaux_1km_reun.csv
        sep : ","
    commune: #https://statistiques-locales.insee.fr/#view=map1&c=indicator
      communes_encodage_2020: 
        path: ./data/insee/commune/communes2020.csv # https://www.insee.fr/fr/information/4316069
        sep : ","
      communes_encodage_2023: 
        path: ./data/insee/commune/v_commune_2023.csv 
        sep : ","
      deces: 
        path: ./data/insee/commune/deces_communes.csv
        sep : ";" 
      elections: 
        path: ./data/insee/commune/elections_communes.csv
        sep : ";" 
      emploi: 
        path: ./data/insee/commune/emploi_par_age_sexe_communes.csv 
        sep : ";" 
      entreprise_creation: 
        path: ./data/insee/commune/entreprise_creations_commune.csv 
        sep : ";" 
      entreprise_caracteristiques: 
        path: ./data/insee/commune/entreprises_caracteristiques_commune.csv 
        sep : ";" 
      logements: 
        path: ./data/insee/commune/logements_commune.csv 
        sep : ";" 
      menages: 
        path: ./data/insee/commune/menages_communes.csv 
        sep : ";" 
      naissance: 
        path: ./data/insee/commune/naissance_communes.csv 
        sep : ";" 
      populations_csp: 
        path: ./data/insee/commune/population_csp_communes.csv 
        sep : ";" 
      scolarisation: 
        path: ./data/insee/commune/scolarisation_communes.csv 
        sep : ";" 
      securite: 
        path: ./data/insee/commune/securite_vols_commune.csv 
        sep : ";" 
      tourisme: 
        path: ./data/insee/commune/tourisme_commune_2023.csv
        sep : ";" 
    deparetment:
      chomage:  
        path: ./data/insee/departement/chomage_departement.csv
        sep : ";" 
    zone_emploi:
      chomage: 
        path: ./data/insee/zone_emploi/chomage_zone_emploi.csv
        sep : ";" 
      pauvrete: 
        path: ./data/insee/zone_emploi/pauvrete_zone_emploi.csv
        sep : ";" 
      pouvoir_achat: 
        path: ./data/insee/zone_emploi/pouvoir_achat_zone_emploi.csv
        sep : ";" 
      salaires: 
        path: ./data/insee/zone_emploi/salaires_zone_emploi.csv
        sep : ";" 

