cleaning:
  path_mapping_country: D:/data/default/mapping_country.json
  full_data_auction_houses : ALL_ITEMS_202403
  artists: 
    origine_table_name: ARTISTS_DB_PRICE
  drouot : 
    origine_table_name: DROUOT_202403
  christies : 
    origine_table_name: CHRISTIES_202403
  sothebys : 
    origine_table_name: SOTHEBYS_202403
  mapping:
    localisation: {
        "london" : ['online', 'onlineonly.christies.com', "londres", "london (south kensigton)", 
                    "london", "www.nathanmilleraste.com", "www.lambertzhao.com", "www.bonhams.com", "www.sothebys.com", 
                    'www.dawsonsauctions.co.uk','www.elmwoods.co.uk'],
        "nan": ['', "nan", '(mo)', '(ta)', '(vr)', '54623', '7'],
        "anvers": ['(anvers)', 'anvers'],
        "alencon": ['alencon','alençon'],
        "athenes": ['athens', 'athènes'],
        "barcelone": ['barcelona', 'barcelone'],
        "berne": ['bern', 'berne'],
        "bruxelles": ['bruxelles', 'www.rops-online.be'],
        "paris": ['paris', "www.millon.com", 'www.online.aguttes.com', 'www.piasa.fr',
              'www.drouot.com', "www.piguet.com", 'www.aguttes.com',
              "https://www.boisgirard-antonini.com/vente/aviation-3/", "levallois-perret",
              'levallois'],
        "bologne": ['bologna', 'bologne'],
        "bale": ['basel', 'bâle'],
        "chambery": ['chambery', 'chambéry'],
        "geneve": ['geneva', 'geneve', 'genova', 'www.geneve-encheres.ch', 
            'genève', 'genèves', "www.kollerauctions.com"],
        "berlin": ['germany', 'berlin'],
        "hong-kong": ['hong kong', 'hong-kong', 'hongkong'],
        "milan": ['milan', 'milano', 'www.incanto.auction/it/asta-0216/design.asp'],
        "rome": ['roma', 'rome'],
        "rosiere": ['rosiere', 'rosière'],
        "saarbrucken": ['saarbrucken', 'saarbrücken'],
        "vienne": ['vienna', 'vienne'],
        "zurich": ['zurich', 'zürich'],
        "la hague": ['www.venduehuis.com', 'la hague'],
        "nouvelle orleans": ['www.invaluable.com', 'nouvelle orleans'],
        "rotterdam": ['www.vendurotterdam.nl', 'rotterdam'],
        "hannut": ['hannut', 'hannut)', "(hannut)"]
        }
    country: {
        "abbiategrasso": "ITALIE",
        "abruzzo": "ITALIE",
        "admiralty": "UK",
        "agen": "FRANCE",
        "ahlden": "ALLEMAGNE",
        "aix-en-provence": "FRANCE",
        "ajaccio": "FRANCE",
        "alban": "FRANCE",
        "albi": "FRANCE",
        "alencon": "FRANCE",
        "allschwil": "SUISSE",
        "amboise": "FRANCE",
        "amherst": "USA",
        "amiens": "FRANCE",
        "amneville": "FRANCE",
        "amsterdam": "PAYS-BAS",
        "andelys": "FRANCE",
        "angers": "FRANCE",
        "angouleme": "FRANCE",
        "antibes": "FRANCE",
        "antwerpen": "BELGIQUE",
        "anvers": "BELGIQUE",
        "anvers-berchem": "BELGIQUE",
        "arezzo": "ITALIE",
        "arles": "FRANCE",
        "arnhem": "PAYS-BAS",
        "arras": "FRANCE",
        "aschaffenburg": "ALLEMAGNE",
        "athenes": "GRECE",
        "auch": "FRANCE",
        "augsburg": "ALLEMAGNE",
        "auray": "FRANCE",
        "aussaune": "FRANCE",
        "autun": "FRANCE",
        "auvers-sur-oise": "FRANCE",
        "auxerre": "FRANCE",
        "aventura": "USA",
        "avignon": "FRANCE",
        "aviv": "USA",
        "azor": "USA",
        "bagnolet": "FRANCE",
        "bamberg": "FRANCE",
        "barcelona": "ESPAGNE",
        "barcelone": "ESPAGNE",
        "bastia": "FRANCE",
        "bath": "UK",
        "baule": "FRANCE",
        "baux-de-provence": "FRANCE",
        "bayeux": "FRANCE",
        "bayreuth": "ALLEMAGNE",
        "beach": "USA",
        "beaune": "FRANCE",
        "beijing": "CHINE",
        "berlin": "ALLEMAGNE",
        "berne": "SUISSE",
        "besancon": "FRANCE",
        "beyrouth": "LIBAN",
        "biarritz": "FRANCE",
        "bilbao": "ESPAGNE",
        "billingshurst": "UK",
        "blois": "FRANCE",
        "bois": "FRANCE",
        "bologne": "FRANCE",
        "bolton": "UK",
        "bolzano": "ITALIE",
        "bonn": "ALLEMAGNE",
        "bordeaux": "FRANCE",
        "borgholzhausen": "ALLEMAGNE",
        "bouchard": "FRANCE",
        "boulogne-billancourt": "FRANCE",
        "bourg-en-bresse": "FRANCE",
        "bracciolini": "ITALIE",
        "brasles": "FRANCE",
        "brescia": "ITALIE",
        "brest": "FRANCE",
        "bretteville-sur-odon": "FRANCE",
        "brive-la-gaillarde": "FRANCE",
        "brno": "REPUBLIQUE TCHEQUE",
        "bronzolo": "ITALIE",
        "brooklyn": "USA",
        "brough": "UK",
        "bruges": "BELGIQUE",
        "bruxelles": "BELGIQUE",
        "bucharest": "ROUMANIE",
        "bucuresti": "ROUMANIE",
        "bully": "FRANCE",
        "bursard": "FRANCE",
        "bale": "SUISSE",
        "beziers": "FRANCE",
        "caen": "FRANCE",
        "canals": "FRANCE",
        "canejan": "FRANCE",
        "cannes": "FRANCE",
        "castellet": "FRANCE",
        "castelnau-le-lez": "FRANCE",
        "castres": "FRANCE",
        "catania": "ITALIE",
        "celle": "FRANCE",
        "central": "USA",
        "chambery": "FRANCE",
        "champery": "SUISSE",
        "chantilly": "FRANCE",
        "chard": "UK",
        "charenton-le-pont": "FRANCE",
        "charleville-mezieres": "FRANCE",
        "chartres": "FRANCE",
        "chase": "USA",
        "chassieu": "FRANCE",
        "chatenoy-le-royal": "FRANCE",
        "chatou": "FRANCE",
        "chaville": "FRANCE",
        "cheltenham": "UK",
        "cherbourg": "FRANCE",
        "cherre": "FRANCE",
        "chester": "USA",
        "chinon": "FRANCE",
        "cholet": "FRANCE",
        "chatellerault": "FRANCE",
        "ciron": "FRANCE",
        "clamecy": "FRANCE",
        "clermont-ferrand": "FRANCE",
        "cloud": "FRANCE",
        "colle-sur-loup": "FRANCE",
        "cologne": "ALLEMAGNE",
        "compiegne": "FRANCE",
        "concarneau": "FRANCE",
        "condecourt": "FRANCE",
        "corbas": "FRANCE",
        "cork": "IRLANDE",
        "cormeilles": "FRANCE",
        "cormenon": "FRANCE",
        "cremona": "ITALIE",
        "croix": "FRANCE",
        "croydon": "UK",
        "cuxhaven": "ALLEMAGNE",
        "d'agen": "FRANCE",
        "dallas": "USA",
        "dc": "USA",
        "deauville": "FRANCE",
        "degersheim": "SUISSE",
        "delemont": "SUISSE",
        "denis": "FRANCE",
        "derby": "UK",
        "desert": "USA",
        "devon": "UK",
        "diemen": "FRANCE",
        "dijon": "FRANCE",
        "dinan": "FRANCE",
        "doha": "USA",
        "doncaster": "UK",
        "douai": "FRANCE",
        "doulchard": "FRANCE",
        "doullens": "FRANCE",
        "downingtown": "USA",
        "draguignan": "FRANCE",
        "dresden": "FRANCE",
        "dreux": "FRANCE",
        "driburg-erpentrup": "FRANCE",
        "dubai": "EAU",
        "dublin": "IRLANDE",
        "durrow": "IRLANDE",
        "dusseldorf": "ALLEMAGNE",
        "edinburgh": "UK",
        "egreve": "FRANCE",
        "elbeuf": "FRANCE",
        "engen": "ALLEMAGNE",
        "enghien-les-bains": "FRANCE",
        "enschede": "PAYS-BAS",
        "entzheim": "FRANCE",
        "erandio": "ESPAGNE",
        "essen": "FRANCE",
        "etienne": "FRANCE",
        "eygalieres": "FRANCE",
        "eysines": "FRANCE",
        "fains-vuel": "FRANCE",
        "farnham": "UK",
        "ferrara": "ITALIE",
        "fiacre": "FRANCE",
        "firenze": "ITALIE",
        "fitilieu": "FRANCE",
        "florence": "ITALIE",
        "fontainebleau": "FRANCE",
        "forges-les-eaux": "FRANCE",
        "formigine(mo)": "ITALIE",
        "fort-de-france": "FRANCE",
        "franklin": "USA",
        "freiburg": "ALLEMAGNE",
        "frome": "UK",
        "frejus": "FRANCE",
        "gace": "FRANCE",
        "geneve": "SUISSE",
        "gent": "FRANCE",
        "gerpinnes": "FRANCE",
        "ghent-mariakerke": "ALLEMAGNE",
        "gironde": "FRANCE",
        "glasgow": "UK",
        "gloucestershire": "UK",
        "goes": "FRANCE",
        "goole": "UK",
        "gosier": "FRANCE",
        "gosselies": "FRANCE",
        "grasse": "FRANCE",
        "grenoble": "FRANCE",
        "grimaud": "FRANCE",
        "genicourt": "FRANCE",
        "gunes": "FRANCE",
        "haarlem": "PAYS-BAS",
        "hagenburg": "ALLEMAGNE",
        "hague": "PAYS-BAS",
        "hambourg": "ALLEMAGNE",
        "hamburg": "ALLEMAGNE",
        "hannaches": "FRANCE",
        "hannover": "ALLEMAGNE",
        "hannur": "BELGIQUE",
        "hannut": "BELGIQUE",
        "harelbeke": "BELGIQUE",
        "harwich": "UK",
        "hasselt": "BELGIQUE",
        "hattemerbroek": "PAYS-BAS",
        "haucourt-moulaine": "FRANCE",
        "havre": "FRANCE",
        "haye": "PAYS-BAS",
        "heidelberg": "ALLEMAGNE",
        "heilbronn": "ALLEMAGNE",
        "hertfordshire": "UK",
        "hill": "UK",
        "hilversum": "PAYS-BAS",
        "honfleur": "FRANCE",
        "hong-kong": "CHINE",
        "howald": "LUXEMBOURG",
        "hagendorf": "SUISSE",
        "ijsselstein": "PAYS-BAS",
        "independence": "USA",
        "issoire": "FRANCE",
        "issy-les-moulineaux": "FRANCE",
        "ives": "UK",
        "ixelles": "FRANCE",
        "izegem": "FRANCE",
        "joigny": "FRANCE",
        "jolie": "FRANCE",
        "jouancy": "FRANCE",
        "joue-les-tours": "FRANCE",
        "juan-les-pins": "FRANCE",
        "kiel": "ALLEMAGNE",
        "klaaswaal": "PAYS-BAS",
        "knokke": "FRANCE",
        "kolham": "FRANCE",
        "kong": "FRANCE",
        "krefeld": "FRANCE",
        "koln": "ALLEMAGNE",
        "konigswinter": "ALLEMAGNE",
        "l'adour": "FRANCE",
        "la hague": "PAYS-BAS",
        "ladenburg": "ALLEMAGNE",
        "ladispoli": "FRANCE",
        "lambertville": "USA",
        "lambeth": "UK",
        "lamotte-beuvron": "FRANCE",
        "langres": "FRANCE",
        "lapalisse": "FRANCE",
        "lausanne": "SUISSE",
        "laxou": "FRANCE",
        "laye": "PAYS-BAS",
        "leiden": "PAYS-BAS",
        "leinfelden-echterdingen": "ALLEMAGNE",
        "levallois-perret": "FRANCE",
        "leyburn": "UK",
        "lhomme": "FRANCE",
        "lille": "FRANCE",
        "limoges": "FRANCE",
        "lindau": "FRANCE",
        "lisboa": "PORTUGAL",
        "lisbonne": "PORTUGAL",
        "lisieux": "FRANCE",
        "livet-sur-authou": "FRANCE",
        "liege": "BELGIQUE",
        "lokeren": "BELGIQUE",
        "london": "UK",
        "lorient": "FRANCE",
        "los angeles": "USA",
        "louviers": "FRANCE",
        "lucie": "USA",
        "ludwigsburg": "FRANCE",
        "luxembourg": "LUXEMBOURG",
        "luz": "FRANCE",
        "lyon": "FRANCE",
        "lesigny": "FRANCE",
        "maastricht": "PAYS-BAS",
        "madrid": "ESPAGNE",
        "magdeburg": "ALLEMAGNE",
        "maggiore": "ITALIE",
        "maidenhead": "UK",
        "maisieres-mons": "FRANCE",
        "mandelieu": "FRANCE",
        "mannheim": "ALLEMAGNE",
        "manosque": "FRANCE",
        "mans": "FRANCE",
        "marbella": "ESPAGNE",
        "marne": "FRANCE",
        "marrakech": "MAROC",
        "marseille": "FRANCE",
        "melbourne": "AUSTRALIE",
        "mesnil-esnard": "FRANCE",
        "mestre": "FRANCE",
        "metz": "FRANCE",
        "miami": "USA",
        "middelburg": "PAYS-BAS",
        "milan": "ITALIE",
        "mions": "FRANCE",
        "moiran": "FRANCE",
        "monaco": "FRANCE",
        "montargis": "FRANCE",
        "montastruc-la-conseillere": "FRANCE",
        "montauban": "FRANCE",
        "montbazon": "FRANCE",
        "monte-carlo": "FRANCE",
        "montevideo": "USA",
        "montgermont": "FRANCE",
        "montpellier": "FRANCE",
        "montreal": "CANADA",
        "morigny-champigny": "FRANCE",
        "mougins": "FRANCE",
        "moulineaux": "FRANCE",
        "moulins": "FRANCE",
        "moulins-sur-allier": "FRANCE",
        "mountfitchet": "UK",
        "moutiers-saint-jean": "FRANCE",
        "mulatiere": "FRANCE",
        "mumbai": "INDE",
        "munich": "ALLEMAGNE",
        "muri": "SUISSE",
        "mutterstadt": "ALLEMAGNE",
        "macon": "FRANCE",
        "munchen": "ALLEMAGNE",
        "munster": "ALLEMAGNE",
        "namur": "BELGIQUE",
        "nancy": "FRANCE",
        "nantes": "FRANCE",
        "napoli": "ITALIE",
        "nazareth": "ISRAEL",
        "netanya": "USA",
        "neuilly-sur-marne": "FRANCE",
        "neuilly-sur-seine": "FRANCE",
        "nevers": "FRANCE",
        "new york": "USA",
        "newbury": "UK",
        "nice": "FRANCE",
        "nicosia": "CHYPRE",
        "nivelles": "FRANCE",
        "nogent-le-phaye": "FRANCE",
        "nogent-sur-marne": "FRANCE",
        "nouvelle orleans": "FRANCE",
        "nimes": "FRANCE",
        "nernberg": "FRANCE",
        "ollioules": "FRANCE",
        "only": "FRANCE",
        "oostende": "BELGIQUE",
        "ophain": "FRANCE",
        "orbec": "FRANCE",
        "orge": "FRANCE",
        "orleans": "FRANCE",
        "ostende": "BELGIQUE",
        "ouen": "FRANCE",
        "ouzouer-sur-trezee": "FRANCE",
        "oxford": "UK",
        "padova": "ITALIE",
        "palerme": "ITALIE",
        "palermo": "ITALIE",
        "paris": "FRANCE",
        "parma": "ITALIE",
        "pau": "FRANCE",
        "paul": "USA",
        "perche": "FRANCE",
        "perros-guirec": "FRANCE",
        "perthes": "FRANCE",
        "peujard": "FRANCE",
        "pforzheim": "ALLEMAGNE",
        "plauen": "ALLEMAGNE",
        "plessis-bouchard": "FRANCE",
        "plerin": "FRANCE",
        "plerin-sur-mer": "FRANCE",
        "poigny-la-foret": "FRANCE",
        "poitiers": "FRANCE",
        "pollestres": "FRANCE",
        "pontchartrain": "FRANCE",
        "portets": "FRANCE",
        "porto": "PORTUGAL",
        "poulseur": "FRANCE",
        "prague": "REPUBLIQUE TCHEQUE",
        "praha": "USA",
        "prato": "ITALIE",
        "priest": "FRANCE",
        "princeton": "USA",
        "provins": "FRANCE",
        "perigny": "FRANCE",
        "perigueux": "FRANCE",
        "quedlinburg": "ALLEMAGNE",
        "quimper": "FRANCE",
        "quintin": "FRANCE",
        "radevormwald": "ALLEMAGNE",
        "radolfzell": "ALLEMAGNE",
        "raincy": "FRANCE",
        "rainha": "UK",
        "raleigh": "USA",
        "rambouillet": "FRANCE",
        "raton": "USA",
        "reims": "FRANCE",
        "rennes": "FRANCE",
        "reugny": "FRANCE",
        "riga": "LETTONIE",
        "ripon": "UK",
        "roanne": "FRANCE",
        "rochelle": "FRANCE",
        "rocklin": "USA",
        "rome": "ITALIE",
        "rosiere": "FRANCE",
        "rotterdam": "PAYS-BAS",
        "roubaix": "FRANCE",
        "rouen": "FRANCE",
        "roye-sur-matz": "FRANCE",
        "rozzano": "ITALIE",
        "saarbrucken": "ALLEMAGNE",
        "sables-d'olonne": "FRANCE",
        "saint-alban": "FRANCE",
        "saint-brieuc": "FRANCE",
        "saint-cloud": "FRANCE",
        "saint-dizier": "FRANCE",
        "saint-germain-en-laye": "FRANCE",
        "saint-jean-d'angely": "FRANCE",
        "saint-jean-de-la-ruelle": "FRANCE",
        "saint-jean-de-luz": "FRANCE",
        "saint-lo": "FRANCE",
        "saint-martin-boulogne": "FRANCE",
        "saint-martin-des-champs": "FRANCE",
        "saint-maurice": "FRANCE",
        "saint-omer": "FRANCE",
        "saint-ouen": "FRANCE",
        "saint-ouen-sur-seine": "FRANCE",
        "saint-piat": "FRANCE",
        "saint-pierre": "FRANCE",
        "saint-raphael": "FRANCE",
        "saint-siffret": "FRANCE",
        "saint-tropez": "FRANCE",
        "saint-emilion": "FRANCE",
        "saint-etienne": "FRANCE",
        "sancerre": "FRANCE",
        "sanremo": "ITALIE",
        "sarzana": "ITALIE",
        "sceaux": "FRANCE",
        "schoelcher": "FRANCE",
        "scottsdale": "USA",
        "sebastien": "FRANCE",
        "seefeld": "ALLEMAGNE",
        "semur-en-auxois": "FRANCE",
        "senago": "ITALIE",
        "senlis": "FRANCE",
        "senlisse": "FRANCE",
        "shanghai": "CHINE",
        "shrewsbury": "UK",
        "singapore": "SINGAPOUR",
        "soissons": "FRANCE",
        "somerset": "UK",
        "son": "USA",
        "soorts-hossegor": "FRANCE",
        "sprundel": "PAYS-BAS",
        "stadtbredimus": "LUXEMBOURG",
        "staffs": "UK",
        "stains": "FRANCE",
        "stamford": "UK",
        "stourpaine": "UK",
        "strasbourg": "FRANCE",
        "strovolos": "CHYPRE",
        "stuttgart": "ALLEMAGNE",
        "suarlee": "FRANCE",
        "surrey": "UK",
        "sydney": "AUSTRALIE",
        "sees": "FRANCE",
        "seville": "ESPAGNE",
        "taipei": "CHINE",
        "tallahassee": "USA",
        "tallinn": "ESTONIE",
        "tampa": "USA",
        "taunus": "ALLEMAGNE",
        "teck": "ALLEMAGNE",
        "tegernsee": "ALLEMAGNE",
        "tel aviv": "ISRAEL",
        "terme": "FRANCE",
        "thatcham": "UK",
        "tilburg": "PAYS-BAS",
        "tokyo": "JAPON",
        "torino": "ITALIE",
        "toronto": "CANADA",
        "toulon": "FRANCE",
        "toulouse": "FRANCE",
        "touquet-paris-plage": "FRANCE",
        "tours": "FRANCE",
        "tourtour": "FRANCE",
        "trent": "UK",
        "troyes": "FRANCE",
        "turi": "ITALIE",
        "turin": "ITALIE",
        "twickenham": "UK",
        "uccle": "BELGIQUE",
        "uitgeest": "PAYS-BAS",
        "uzes": "FRANCE",
        "val-de-moder": "FRANCE",
        "valencia": "ESPAGNE",
        "varenne-saint-hilaire": "FRANCE",
        "vaux-le-penil": "FRANCE",
        "veel": "FRANCE",
        "vendome": "FRANCE",
        "venir": "FRANCE",
        "venissieux": "FRANCE",
        "vernon": "FRANCE",
        "verona": "ITALIE",
        "versailles": "FRANCE",
        "verviers": "BELGIQUE",
        "vezin-le-coquet": "FRANCE",
        "via": "FRANCE",
        "viareggio": "ITALIE",
        "vic-sur-seille": "FRANCE",
        "vicenza": "ITALIE",
        "vienne": "AUTRICHE",
        "vilbel": "ESTONIE",
        "villefranche-sur-mer": "FRANCE",
        "villefranche-sur-saone": "FRANCE",
        "villeurbanne": "FRANCE",
        "vincennes": "FRANCE",
        "vougeot": "FRANCE",
        "vesinet": "FRANCE",
        "warsaw": "POLOGNE",
        "wassenach": "ALLEMAGNE",
        "wavre": "BELGIQUE",
        "weiswampach": "LUXEMBOURG",
        "wien": "AUTRICHE",
        "wil": "SUISSE",
        "wilmington": "USA",
        "wiltshire": "UK",
        "wingene": "BELGIQUE",
        "worms": "BELGIQUE",
        "wurzburg": "ALLEMAGNE",
        "www.christies.com": "FRANCE",
        "yon": "FRANCE",
        "york": "USA",
        "yorkshire": "UK",
        "zaragoza": "ESPAGNE",
        "zaventem": "BELGIQUE",
        "zofingen": "SUISSE",
        "zurich": "SUISSE",
        "zwolle": "UK",
        "eguillly": "FRANCE",
        "evreux": "FRANCE",
        "uberlingen": "ALLEMAGNE"
    }