gbm_training:

  save_model_path: ./data/models/price_prediction/
  seed: 1234
  train_full_at_the_end: True

  vase:
    model_target: "EUR_FINAL_RESULT"
    model_weight: Null
    model_features: 
      - NUMBER_DESCRIBED_OBJECTS
      - VASE_HEIGHT
      - VASE_MATERIAL
      - VASE_YEAR
      - VASE_DECORATIONS
      - VASE_SIGNED
      - VASE_CONDITION
      - VASE_STYLE
      - VASE_COLOR
      - VASE_COUNTRY
      - VASE_SHAPE
      - AUCTION_YEAR
      - EUR_MIN_ESTIMATION
      - EUR_MAX_ESTIMATION
      - SELLER 
      - CURRENCY 
    categorical_features:
      - VASE_MATERIAL
      - VASE_DECORATIONS
      - VASE_STYLE
      - VASE_COLOR
      - VASE_COUNTRY
      - VASE_SHAPE
      - CURRENCY
      - SELLER 
    cross_validation:
      n_splits: 5
      
    model_parameters: 
      objective: "regression"
      eval_metric: "mape"
      metric: 'mape'
      max_depth: 7
      min_data_in_leaf: 5
      colsample_bytree: 0.75
      subsample: 0.75
      learning_rate: 0.008
      num_iterations: 2000
      lambda_l1 : 0.1
      n_jobs: 7
      verbose_eval: -1
      verbose : -1
      early_stopping_round: 50