gpt:
  save_path: D:/data/llm_extracts/llama3_extract_paintings/
  llm_model: lmstudio-community/Meta-Llama-3-8B-Instruct-GGUF #"gpt-3.5-turbo-0125"
  seed: 1234
  introduction: "You are an art expert. Extract following features from the painting description with a JSON format. Only return valid json and nothing else. Write all JSON values only in english, translate them if necessary." 