FROM python:3.12

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Create a non-root user
RUN addgroup --system celeryuser && adduser --system --ingroup celeryuser celeryuser

WORKDIR /app
COPY . /app
RUN mkdir -p /data/models
RUN mkdir -p /data/default

RUN apt-get update &&\
    apt-get install -y apt-utils &&\
    apt-get install -y gcc

#Install requirements
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
