server:
  host: host.docker.internal #postgres_db
  database: postgres
  port: 5432

email:
  MAIL_SERVER: smtp.gmail.com
  MAIL_PORT: 465
  MAIL_USE_TLS: False
  MAIL_USE_SSL: True

front_end:
  server: 'http://localhost:3000'