server:
  host: host.docker.internal #postgres_db
  database: postgres
  port: 5432

front_end:
  server: 'http://localhost:3000'

product:
  free_plan_days: 7
  initial_closest_volume: 30
  initial_search_volume: 30

plans: 
  free: "free_plan"
  individual: "individual_plan"
  expert: "expert_plan"