export const URL_API='http://localhost:80'; //middle api nginx
export const URL_API_BACK='http://127.0.0.1:2000'; //backend nginx
export const URL_LOGIN='/login';
export const URL_SIGNIN='/signin';
export const URL_UPLOAD='/process';
export const URL_GET_TASK='/task_status';
export const URL_GET_IDS_INFO='/ids_infos';
export const ROOT_PICTURE='http://localhost:4000';
export const CARDS_PER_PAGE=36;
export const COMPANY_NAME='Artyx';
export const URL_RESET_PASSWORD="/reset-password";
export const URL_GET_TASK_RESULTS="/get-past-results"
export const URL_SET_NEW_PASSWORD="/set-new-password";
export const URL_DELETE_TASK_RESULT="/delete-task"