services:
    postgres:
        container_name: postgres_v2
        hostname: db_v2
        build:
            context: ./
            dockerfile: dockerfile
        ports:
            - 5434:5432
        expose:
            - 5432
        environment:
            - POSTGRES_DB=vectordb
            - DATABASE_PORT=5434
        env_file:
            - ../global-schemas/.env
        volumes:
            - ./init.sql:/tmp/init.sql
            - pgdata_v2:/var/lib/postgresql/data
            - D:/db_backup/database_pgdata.tar:/db_backup/database_pgdata.tar
        networks:
            - shared_net
        restart: always

networks:
  shared_net:
    external: true

volumes:
    pgdata_v2:
